app-template:
    ingress:
        main:
            annotations:
                nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:H5Ncb2zGz4EpbIlGdI9vrJ58TmD0eF6xm3bJ,iv:zv/a/M9pxL8c/koISBG4CTDAKMH8XJcyDveZmFXMS+M=,tag:hs8AwY0Z9lUV1GdrL4vHEA==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:lxcF7tS0d8wJHiUd6s2UUA==,iv:dJo+pvSM8iT6JwUYac3JH8GpSFXNEfnDge3AVH5Y7Vc=,tag:i2c5aDsDZthT+KYdq1L36w==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:4Q==,iv:QHwjgN+BZtqtalPBIg5Fm1BdQDYWXUqHZSy5hWSIEKE=,tag:FH6ndaL4L3FEjH6CJJ/O5w==,type:str]
                      service:
                        name: ENC[AES256_GCM,data:ZUAVPw==,iv:bA7m3bs6P83CD7DGVllqn7TPoVG8wxeOQCYYSsDv4zI=,tag:dihKSRx2PHSoK1wbvDXvfA==,type:str]
                        port: ENC[AES256_GCM,data:7Mjw4g==,iv:WP5VEjWw4PICwD5/aI34pzjn4hcGBXeve4v4X5r8U0g=,tag:mh2sJwV4BUFdFNM4Lu4GDA==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:H4fZrzYoW7B9QR+PeDa/jA==,iv:UjiRa4Hqnpigu/pn+rav1s7M9PARv1PHt+6SXdMFXf8=,tag:hguOBUhZ12YeMig7RssAkA==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UlFjZnU2QkN2SjhLY0g0
            UXF6SmNnWFlHMVhKWFoxVzJGRmYvR2h5NkNVCmxxUVlkem0wbDFSK3R6QmFyVWRN
            Ym5NcUxhaUZQRzdibDIyQjNKZDBFbEEKLS0tIHhyRmJjRmxMR0QrRks1MzZWbkp1
            ZUJnNFJVSjVSSHB2TCtFdlhkemIxUEUKLKOkm4eJ6uHJMcu+jtcj7z6wxyOStTiH
            Nm3h5OPgsRFhi+1u5q02x1bdnbqbZy2ASdEHGJQBWL4t0zZvFNlQSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T08:20:18Z"
    mac: ENC[AES256_GCM,data:AtcpHPDpKCVgaBo4obGW3/nmIXCMUPU2waurXOwxE5xdxdZvCaLQkmgVTksRvObBbWOgbqnGwwiGvJP6Gfqk453zWJ0tQyofw26wGaUZ7eyaujFOR+nmuzrzh7pLvHHoqeeXQSNQGK8ZGfVKCcTpJqsCT2KYzumD8hK6TlKjQfY=,iv:H2YmutnXCNbPZl8mxSnFupIHGDSfvAJ16STx/wpoWWo=,tag:T1S1lRqTeJNombn6V2K0Eg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
