volsync:
    repository: ENC[AES256_GCM,data:KiaKRM3zyFy2da67L7tAAcp9wR2MGmL3V+hfyxSIenulPoEHaffRMw==,iv:vB20zdiUHmQei+BwvAGTjMSf/FYt/jknsLmLur9gIn0=,tag:R5qdWZ1KSe+pi2+C2OeJsQ==,type:str]
    password: ENC[AES256_GCM,data:gu2BHl3DwTzxQ6tcHxFVch8V2ksQUD/RbA3l2zFPtmM=,iv:QGcsiFnR2UkeRwGTo1180FMAh76CSIUj/1DAL225r0E=,tag:W2NzwrbaeWUAeOWoiP/OVg==,type:str]
    accessKey: ENC[AES256_GCM,data:jW5eiz54v0Xn5ge3qY0mJA==,iv:fi9rIlu6BKobRyg54+F8WRZNxPHwrqZC91OSuxZexyo=,tag:3Z095Tb47XnZffQR/QHTaw==,type:str]
    secretKey: ENC[AES256_GCM,data:SJK7QbhlF7Du5buHik+TB2ELbnB1lVXLvzPmygafAvQ=,iv:gaamTtYA9oEA0HUxpv30k8G6u96aP0vYc16UEj3CC64=,tag:7Lv+weE43lGl35n+Ol6SJA==,type:str]
app-template:
    ingress:
        main:
            hosts:
                - host: ENC[AES256_GCM,data:vo2NuaFpf+ufcf0OtRtS,iv:2E3M+Jp/uzX+SM5CfhEifGvQKinzpcU8XoJ5aBBe6hI=,tag:Lf/BBQYWaPf2WodOYL3xGg==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:2g==,iv:+QiPpDSlYUPlPbr+QTtRHVn6kCWw3MTZ0eSQi7vFHBM=,tag:EApDZDmFLUsOVvVcg6oT9A==,type:str]
                      service:
                        name: ENC[AES256_GCM,data:Be6nKQ==,iv:gsg0rOQLVyudDket1vevOf4uDNNOxL0DN2wVOmBdkmc=,tag:Y0BiYzJG5r3/xAHFeRR6Dg==,type:str]
                        port: ENC[AES256_GCM,data:nIFUPg==,iv:e6cAdV+EStkwhVRp7ALzlVVxeoYj+6EAOvX5svTAQyQ=,tag:xVioAQfG+6ocO9P2D+0Adg==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:OT4qDS2JpMbo8vA5vy+o,iv:QK7R7ehkBU7zmr4blPvhizNPR+oYiN6bPmW+vQIKnrE=,tag:IMq/sTErPDeEnqXRFSxGMA==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dnRtdXdhdjg0eXV2Q2Rv
            bVZhdURVclVNQ3ZWdXdDRkZQL3h5YjdoY1ZvClJOZnIxVnZiOHk2UkJCY2RQRkZY
            OCtRRnlKRmVVMldxMDF2eW5PSXo3cDQKLS0tIEJPcUdDdkFMRVFDbkdibVVBWHZP
            bzVlY0kyNnd4UjhFbUhWaFZ2TWRJY1UKYu04y/FSJQWVs0Fd/Cs2g4sag1iipoaz
            Iqs3LNoZGYb1mA4eyYceylkxvDepJE/rbMe7GBNsYIonUxU7WL5x2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T21:13:18Z"
    mac: ENC[AES256_GCM,data:yyefzP8Cm1GSxw/lxm2FJ9dOxuFeE82Q+fwoau9EP10fek+U3zU311bpMV0PLvGN6GdVrYsbd2T4uDyCWf77aprUZ8nMxhSQ8wRS+9SnY+wjaDxP7URgcxJddwyW0A3Zc3/FDk2okbDawPvHzSpUJc0UubhCGd/o+hp+aszqKrw=,iv:tA4u6UJAtit80+T1rbjPTprQflNgkiXU823TWIzsw34=,tag:1zMkfcg+2bNb4KKG6zKi+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
