volsync:
    repository: ENC[AES256_GCM,data:KiaKRM3zyFy2da67L7tAAcp9wR2MGmL3V+hfyxSIenulPoEHaffRMw==,iv:vB20zdiUHmQei+BwvAGTjMSf/FYt/jknsLmLur9gIn0=,tag:R5qdWZ1KSe+pi2+C2OeJsQ==,type:str]
    password: ENC[AES256_GCM,data:gu2BHl3DwTzxQ6tcHxFVch8V2ksQUD/RbA3l2zFPtmM=,iv:QGcsiFnR2UkeRwGTo1180FMAh76CSIUj/1DAL225r0E=,tag:W2NzwrbaeWUAeOWoiP/OVg==,type:str]
    accessKey: ENC[AES256_GCM,data:jW5eiz54v0Xn5ge3qY0mJA==,iv:fi9rIlu6BKobRyg54+F8WRZNxPHwrqZC91OSuxZexyo=,tag:3Z095Tb47XnZffQR/QHTaw==,type:str]
    secretKey: ENC[AES256_GCM,data:SJK7QbhlF7Du5buHik+TB2ELbnB1lVXLvzPmygafAvQ=,iv:gaamTtYA9oEA0HUxpv30k8G6u96aP0vYc16UEj3CC64=,tag:7Lv+weE43lGl35n+Ol6SJA==,type:str]
pocketId:
    appUrl: ENC[AES256_GCM,data:ijm7enuPiZz1ckp+PQea,iv:6d8Vq18bqIN4zzG1BKhifq6R27WgYPHI8SOrOMh0d2k=,tag:PF+tNLKfckLeGNmSCpIrkA==,type:str]
    encryptionKey: ENC[AES256_GCM,data:PQkGNVPOeLY5buzjKWuJtGYhw/8T,iv:10pQpV08ycnU3MFchz2DHaEBUlsrqv87YYF05QPaZBc=,tag:DHWznLzE2zMHmzz9c1tSWw==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:rcnpXgBoUElxTuXFx8wUPTI=,iv:w1fffqXHW+IKZ245DY+74fCNIDEUWAl2m+ccAkpNGNw=,tag:+HjLf8PbRqv7ojzXS/KgNw==,type:str]
        port: ENC[AES256_GCM,data:RG2+,iv:nHIA1DKn63IWN9Nr9F8CMScvjleGRpVNBnANRBrlcHw=,tag:2Y4iC5TkVbXH9MYXLdZvjw==,type:int]
        user: ENC[AES256_GCM,data:iIYb0GDX55UXHw3vrmKUv6g=,iv:P5vQ8u69utfrkam7LXcEjeCg26pTetibhDHIyhcUFWE=,tag:4iHHi376yDPc+wlGvcBF+Q==,type:str]
        password: ENC[AES256_GCM,data:WGQo9l8ss1ucuGas9sWc1Q==,iv:LdL1rfD8dOvkU5cizLIWW7KxneQKAM3L+hpHjjOWOK4=,tag:80SFILZYbplMjjV1oPgJow==,type:str]
        from: ENC[AES256_GCM,data:8dEh2BRJFmKuJ+NJse/0,iv:gq176yRcFhSqEAj4F06A+zdpiHPol2ErLJ0T+Nn81P4=,tag:ezmJQuOXFoJCxiLq6Aq8FA==,type:str]
app-template:
    ingress:
        main:
            hosts:
                - host: ENC[AES256_GCM,data:vo2NuaFpf+ufcf0OtRtS,iv:2E3M+Jp/uzX+SM5CfhEifGvQKinzpcU8XoJ5aBBe6hI=,tag:Lf/BBQYWaPf2WodOYL3xGg==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:2g==,iv:+QiPpDSlYUPlPbr+QTtRHVn6kCWw3MTZ0eSQi7vFHBM=,tag:EApDZDmFLUsOVvVcg6oT9A==,type:str]
                      service:
                        name: ENC[AES256_GCM,data:Be6nKQ==,iv:gsg0rOQLVyudDket1vevOf4uDNNOxL0DN2wVOmBdkmc=,tag:Y0BiYzJG5r3/xAHFeRR6Dg==,type:str]
                        port: ENC[AES256_GCM,data:nIFUPg==,iv:e6cAdV+EStkwhVRp7ALzlVVxeoYj+6EAOvX5svTAQyQ=,tag:xVioAQfG+6ocO9P2D+0Adg==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:OT4qDS2JpMbo8vA5vy+o,iv:QK7R7ehkBU7zmr4blPvhizNPR+oYiN6bPmW+vQIKnrE=,tag:IMq/sTErPDeEnqXRFSxGMA==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dnRtdXdhdjg0eXV2Q2Rv
            bVZhdURVclVNQ3ZWdXdDRkZQL3h5YjdoY1ZvClJOZnIxVnZiOHk2UkJCY2RQRkZY
            OCtRRnlKRmVVMldxMDF2eW5PSXo3cDQKLS0tIEJPcUdDdkFMRVFDbkdibVVBWHZP
            bzVlY0kyNnd4UjhFbUhWaFZ2TWRJY1UKYu04y/FSJQWVs0Fd/Cs2g4sag1iipoaz
            Iqs3LNoZGYb1mA4eyYceylkxvDepJE/rbMe7GBNsYIonUxU7WL5x2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T21:49:34Z"
    mac: ENC[AES256_GCM,data:O+Jl3+FbvP8QhojD4ehVekD7XhVgc/hiPeaQ5Y2ikKQ4uE+LrBVfK0wyF/8hzKZ+4o34jebSfcXFXvsVR9dqkCICMVIk3tUvYK7k0qUE0nx5CQWe+VCdtLiTcn/KsdQ/8bbEebrX5K0SnwLNSvRzahmOMnAonmqSek6+oUvNzTU=,iv:g4xNIKHKZr+c8kDm/74aghzHJ5uZKMJiB3lDTW66S9I=,tag:IhiXC87XzyFMeVXgET5keg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
