prowlarr:
    apiKey: ENC[AES256_GCM,data:JONZU75+CPp20KdUgtCribJQXJ3YeIap1M8xdK9rU58=,iv:bGb1xC2GSFEe2iUhAyCsy+tmRAMB5/XzL8DgqSinWvk=,tag:0CrTr+/mG1osQKB2J0aRAQ==,type:str]
qbittorrent:
    url: ENC[AES256_GCM,data:IASPyWme4993jovA03WcmS2Sy/l5aAYJbqRUf/v//1WuYYLvz0MnVVkdZFB0MqE=,iv:DAAUIFpxuehi56Nqij4WJ5LJuWMcfJtAjSDeq12ncQ8=,tag:rXCH8Jcn+73p0DmEH+8SVQ==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZVRRZWxHcEFpN3lsT3ZY
            eWsvSW9kY3dMSnBaSE5aanVDbnlLY1RIU0ZBCklrNjB3U2VwVGp3WUVrUkJHalRH
            VzVBd2NLSzVLS3RnYUQ2V0dVclhDRDAKLS0tIHc2MENUbldlRUVyYkNnTDdWRS83
            QWRFNmYzRkxGVm9oOTllemRvN011c3cKPXRMch78EpApbGaRKnHF+iFKqCdk0YqT
            JgwZMfACvc2aekluebKYGcdkQm/fULYJztr3UzXJY5Fgoixr3G76YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T09:05:54Z"
    mac: ENC[AES256_GCM,data:zDLMeB+1bezAt2oNVxicfkgWV47+ZNOUZVVaHqehDn/qd+5r+IKTQNeBF/braKNJAhR3OYgAwoCJU8reY1n7RM9DSc7wcmXtop/nCyVNGnD+Za5x/9Vx+Ywo71gkcewzf3JVur2NUOMNhZswfD1Y4IekBwzs2g/UC9yNCnWeIhk=,iv:p3tpQV0aOewLup6E4dhjEUTxmeZueCntUmAZz8vqAgk=,tag:S/Tx/LgG3L4Y3bRhpz88uA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
