volsync:
    repository: ENC[AES256_GCM,data:SMTncDw4amGcK3Id+hJyHHZ/d9Ii6a2pH1/kJZ5OmNzB+JaRWGKJqg==,iv:h+rbE0JfYVtfeMJlXp61KrnI+v4fTCl9iN6NJqbFLbg=,tag:8SIUegiag+/bY6vmE690qQ==,type:str]
    password: ENC[AES256_GCM,data:iSp+bUCfgtp+mbjdkFYWFOraZolSVX1nEKomPdhQa6o=,iv:Nnt+uPhYxsI21YMWf8mAJ6vBzFGlgyD9oQqTlqEArq8=,tag:buB2laKzmPYPDyiiYtJRlA==,type:str]
    accessKey: ENC[AES256_GCM,data:vv2fgzmzdPy8GmA6dsrV5g==,iv:+h2CYzlK+/HJPnR2WA3VtO/99lCIDKnevyC5LaMjd8E=,tag:0th6WHoFzCDN63WVdaYY4Q==,type:str]
    secretKey: ENC[AES256_GCM,data:hGY+aWVjrUhCA4y0GEiu6Z7rJgHQJj48ZC/RG+LgFTA=,iv:GXKli9mtnXGlCtMmzVOJUoColDHK+dYNfhyrAtC+Ki8=,tag:a5MEYBNA/RTLM2fJLH98qA==,type:str]
grafana:
    ingress:
        hosts:
            - ENC[AES256_GCM,data:t6uIfkcC2/zx03My8zjA7g==,iv:nUJQZH0MuUagGMCPwihXsqKohTiv0040px/I9dM6jZ0=,tag:aiEUm45mwqjFuQ4/xZRxDw==,type:str]
        tls:
            - hosts:
                - ENC[AES256_GCM,data:0+VoKtNoGMwmgkKt5gJCmg==,iv:XV7h3F/1CfImjYu6HWHZnsD6r3gA8woxu4dJ8mZVcK4=,tag:s3ozARaQHjicfC5P4syB7A==,type:str]
    env:
        GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:8lZPuA2bvFEdbQ1n+l1sjMV4JSwKDR2lovCtQ50ytmHu3XHMPFQFJlQ=,iv:zksfqmhSNVR10p8VJ5lAcGFV70Fql4nNVnP/0iistHo=,tag:SP5BoJ93YSGJiZIgZj3aTw==,type:str]
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:UXdtcjA9NCWtln9NhgJQNtyYdX/AZvMwXlrIneJ5iuRA,iv:HERA9UKXLclqjfRbZUhrFJlEvscgisfp3H8D2FRAEt8=,tag:DIWfqTGWFOJCvjHNEGTvfQ==,type:str]
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:B05zhQy1heWzG8+kMAiYdHWs52wqUBBcIzBB8oSUUuJ7yChS1o8=,iv:LNfJmeTGTHChSgZxHtAPEWn7trPu6Skbcmr06H7iROM=,tag:uiZCHFgaBzNRZCcUVsqdXg==,type:str]
        GF_SERVER_ROOT_URL: ENC[AES256_GCM,data:gF8I/nfbXg2BBGAoh/URdx3+q3qMuZUq,iv:kCm++syNl9o2v7OCX3h1hq2ydRr8ELpfdadhp0c7zEI=,tag:HFxgrLhUj8QLszTQ0BVrzA==,type:str]
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8JU7+n1k9jw6WD5oNDxnQowNdcCR2LAloTD42/hgd1U=,iv:dbA1ae5F3/CtWVrLFQ7zMGNGiFfV5Sqli1j/abq1yts=,tag:mw2lIYYgLrWzziVvlbICWQ==,type:str]
    grafana.ini:
        auth:
            signout_redirect_url: ENC[AES256_GCM,data:1065du1aIziudT+LFMDMrCfhxVWJD80IAwlLCATv,iv:tvC+KbV2DDYWh8HrdpRGrDMp38ARFQ4yefGjUN5KZ8E=,tag:Jbnu4s2dQLFSMy8FpYvbqg==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYkFkMGVQdlJ4VmsvWEVp
            ems3SXkydmJyaG10Z3lDQVc2cm1rWUJKMUFRCnM2cXBSem9UUEVQN3d0VkdYQmRM
            Uldob3M0Q3dLUDg4WVNuMDFRaHIrTEEKLS0tIFEyMlRyTzRyTWpHRWtPZmkxaU9s
            T0RSOHlaa2ZNOVczTjlZVWRGbkc0ZjAKlyINTXqw+NA51TJ8m8xIdcNxxUFS8avq
            +fEsuPZWUhzbRWMePJeYHLXbjVIRr1JxZ8y49j1seKNpqGHSo+Dkiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T08:34:12Z"
    mac: ENC[AES256_GCM,data:eJZDBdUeiJNXJZXF8jaq9hvDqE+sQt/a3nKAxxNSH2XYdq9GbWs+vrxba0lJXXXKBy0ECr/iIwW9c3WPV1n1McTXDt+YDdYX52xNQdr07tBdqCEvZyEpx0fTCaL/15ymzZdY+1dcoIZzIvdXTzOW5DHRAd+M+xn0R0Ykrkgv70o=,iv:0HPggzp4W3hj2qdCM+K0f+3Frsk2zwoEEozyYAFGLSo=,tag:JWifS6mOhDopPB3FtgiFDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
