glauth:
    baseDN: ENC[AES256_GCM,data:ciAc1f/mpxBE5xF+ha849Wk3FzcF8Q==,iv:vpXqtV0yn93J1a+WzkPot24upM8IliJTmeyNUQenzMY=,tag:Bc+gKgA7C+4KaFe95bPazg==,type:str]
    mfinEmail: ENC[AES256_GCM,data:asRC3FIz6DhyfyHGrBhw8QU=,iv:KwqMCLT8wFZ//DPPR+Iv1oesClXWjhJxn3HDndxW58Q=,tag:tsYdYvCh7Q56iyXiFkzTNw==,type:str]
    mfinPassword: ENC[AES256_GCM,data:KgUV2btigVqw84GZSSkV573AHN6ZrhSJwUozdmzC/3SRwMvYh6rO1P9wiqlxtPsoJqZPV32TFyxKuxHCp2cOU8QyVsPH2hslCi+Iifl9kTD1P+7tRoJSz02efmUZzeJcCFkT2uM6WqkL2wjRGI4OzgO1IhGQbRFs,iv:Sg4q9V37YOzqoF7ZvggVHrqCh/nL7d57hVIKtUY1q5U=,tag:qzcGtYtzPygDxVUjidM90Q==,type:str]
    searchPassword: ENC[AES256_GCM,data:jGJgOC8povl2v5QRNe3YM4ZSTdEMTirnZIj2Inb0JX7xZhMd/5uiHO3bUO/bkW8y8pPYbjNsEluYPdNeLJYt3fZK00ULQ47WoM1Shrx24NUfMLp2UPr1P9gaFeYe9mYozSn49k2KD5/p9G7WAZXTsUvPtxujX5OE,iv:UQZ1iWDtTPXGw5+4EImXoTAZ6QAi2mfYIN1Afz6wQqE=,tag:MX4AVQxeN6I86Mo52CfYTw==,type:str]
    authelia:
        username: ENC[AES256_GCM,data:yqrskFfwOhU=,iv:Yf/BKDpS+Xf551iq8PaFzTK8s5grTabM/pkfYUGmjas=,tag:Rejhkx4BNAZevhj2QzGoZQ==,type:str]
        firstName: ENC[AES256_GCM,data:hj2vf+kcnQA=,iv:sj5weffvsIHyvojicf0meV/sSyg4lXInIsQqU0hfwsY=,tag:f1oui8r0LuoqGf44TfRhOg==,type:str]
        lastName: ENC[AES256_GCM,data:epiiUg==,iv:UwdVj4k3eik79JfL3abwA0tFAe8lbG9/6pcjSQ+JaqI=,tag:e+YptNAfIkAMsCjyZl1HJw==,type:str]
        email: ENC[AES256_GCM,data:DiVDOLQ+JqM6pwmP7Q==,iv:BCddLl7L1BBReYdgC/s1mN0lEVqzb8hDOzXOFrPTEvY=,tag:mO6Xx8PD3s5Bo/aFm6nc4A==,type:str]
        password: ENC[AES256_GCM,data:KM4qots2u7beG9WoqO10q8C98Q95wL02i50B4zUA8ySowwQbwf3c7FLSTvsHT8o600mO032vUpPPAYCkj1uMYTkIqe0dTS1acnEUQjwCwfPz3sTDqwW15c8PzL+ow1Zd0j3PWen9Cf4nzsNZFGl00UyOCSRm5DAI,iv:+IrV/RLsJWhHvCg1dyXA3gG6JR9lZCCLTD1cYwsMSHU=,tag:jjq4yj8mcnlS0Hx7LMKpJg==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dnRtdXdhdjg0eXV2Q2Rv
            bVZhdURVclVNQ3ZWdXdDRkZQL3h5YjdoY1ZvClJOZnIxVnZiOHk2UkJCY2RQRkZY
            OCtRRnlKRmVVMldxMDF2eW5PSXo3cDQKLS0tIEJPcUdDdkFMRVFDbkdibVVBWHZP
            bzVlY0kyNnd4UjhFbUhWaFZ2TWRJY1UKYu04y/FSJQWVs0Fd/Cs2g4sag1iipoaz
            Iqs3LNoZGYb1mA4eyYceylkxvDepJE/rbMe7GBNsYIonUxU7WL5x2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T14:58:10Z"
    mac: ENC[AES256_GCM,data:8qwQ1wB8muEK4vm+Y5rpsqzi/13yESYTYCe5MgzbvvbI+D0P/KCV+5paxzz7rGcLGFh7hfo/j6LZmBPoCCjA7VY8XBijn6Aien5uYTMOsFKORBijQZsvOBJrEHmL+XhXpeSKNZs/0SPIYiwoHfrQaJFEDyX9JFlKq4s+s0LvdgE=,iv:eja065s6zdIvB/UWXyMHOZSlRaZfO4fnnCnigZmRxvg=,tag:tqnbXwNT+EOzlgTE1/6qrQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
