volsync:
    repository: ENC[AES256_GCM,data:2R0D2OgkqShn05Qasq59sRgQk3R++R/93aXKM38o1rzMXd6/Xgjw3w==,iv:9SiV3LjY2SerJdIoZ5q+sWhRwcxvjoRjxZPpdEINLdI=,tag:8/TP5+EDEAZ8HgKzecr5yg==,type:str]
    password: ENC[AES256_GCM,data:jMuLe/XYcvEw3xzpiBQZ7XuNPV8SisYjeDcHGqV9hIM=,iv:5LaQXBHt9P34TiRZTvG+sznuEV3tNNwjCSh6cO/iSmQ=,tag:nfhDo0inoVxzKDgavLNP6g==,type:str]
    accessKey: ENC[AES256_GCM,data:W/6ZUdRiDSRdHymN5QU/Rw==,iv:8Oj/ljdH464x7QkwhVwz59G2cr0eirPt9Zn4mJtZ8WQ=,tag:bCaDAnXFFwn34Wg9vuI19Q==,type:str]
    secretKey: ENC[AES256_GCM,data:g70q5gzHuhbDhRCOw/LvJsoHHKH79D6BlqFJMeTHnww=,iv:1OOmDq+qmAV1cqPggLuKRg1b7fQRnKyhNZECG4KxhL8=,tag:6Uw+zuOkEdTWQI4Q41CRrw==,type:str]
prowlarr:
    apiKey: ENC[AES256_GCM,data:YqinXEfB6ngSrzu24MkiSJ7yYlK/VlSp/RF48kMSLXU=,iv:orj+Nu4BGf21VhCkhRBe6axKwkBkdYrr8fmpjbdXXS8=,tag:+rwxhEtd/pdvtxj2VMdBfA==,type:str]
app-template:
    ingress:
        main:
            annotations:
                nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:JwzcJpJ9Jw3M5cTxRBE6GY9qNYkIRzFllgLN,iv:Bov1wexZPm4Z1wF/NU+bONAlr0gsfvI+YMsAbDZRL9U=,tag:XPG/C6pp/Rt/9sxGsSK0Tg==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:GfzgcvtSkLuBM5XYvXMCwKM=,iv:ejI9Dr/i/PTYcOrSvACtpZem8FdrMBY1+RoVbNDhOYY=,tag:UyY5SMSeSrbLnHV1FXW+DQ==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:uA==,iv:3iPVsvqfL+pmouLiodI6wZ7mcvifnn1ZYxdbNJps4A0=,tag:j9L1hriHFLLHDvPLZb9XlA==,type:str]
                      service:
                        name: ENC[AES256_GCM,data:IUaUHA==,iv:wlhVjCqmayn2Wa97gCT+6ZuKtvW6KBq3DRI9IpevRtE=,tag:PJy9a0YheGi95JqS99a0Hg==,type:str]
                        port: ENC[AES256_GCM,data:njUcQA==,iv:LRCnpyI3ImBClEUDbDs/QkMKTi3VO76GJumVhanBncs=,tag:ZikuHzoJBSyeGrj1FDw98A==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:BPaM5hfZbWM9M4HbFF03jVY=,iv:dZQUoSWEZnMVMruQCXPiXVTETqUvSq9005+apTEcufQ=,tag:6iCDecNOC21h+Oy3T0QzOg==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SWZ1NmVHTndiOGx4Wlcv
            d3hvaFZKcXgxTFppUzVqdkRQY3VUa2hOTTJzCnFkOEhQUkVjVW96UlQyTkJSbTd2
            RWY5U1BxVk16cUR1ZkVBNFdyZ3Fvc1kKLS0tIEpNdVE3OHNZTzdQeUJuNVVGbDIx
            TzRYWlFKRWlCaFJTYVRnbnFqRitHMFUKwP0vodJttQy9DCTnVFTD1LEcNDOzyAf7
            R14IrIA7/KaMyboj8hWtrfMiAia2I3NifKZzOBVG6QWD05fHOU1rmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T08:21:53Z"
    mac: ENC[AES256_GCM,data:o9xZg3x1be45q6441PTPIfp/kFhwnfkTF42LcUtPtjs7deEcSPhp+VA/O9vvf3zrbJVYst6v0xPUCG5nVifrnI2gqbYimGWX5J60mXffH17CBCAQBeBVEkBxlupUrxBoUh5M6EhuXEddEM+Nx2O9hLkCvuEER6s54YhxsXG38cc=,iv:BRN25jWqMlfUdOgLXLNy4rV6p9HDmENR7Yqa2eczED0=,tag:2rGOXYe75/6vDti+V5bGKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
