cilium:
    hubble:
        ui:
            ingress:
                annotations:
                    nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:rAFuIg3iekmD5HC4wA4lugN7LCcv8w3rF8wy,iv:7UCSXO/T37XUfWS+FNEVeLbg/uWFW9lwoNQjcolzwh0=,tag:sWI2Z1CrQYywYkO7J75O+Q==,type:str]
                hosts:
                    - ENC[AES256_GCM,data:pjoWwYtlCBeAxSt+Q9Zx,iv:fBYZb5KT0cylpiwti4hoPJnRtEoNfNZb5h4L9gYmXKE=,tag:B+FzVb77g8crJ8yNg3m1ww==,type:str]
                tls:
                    - hosts:
                        - ENC[AES256_GCM,data:f3pUsa169eNnqboEac3A,iv:3IbXdLJvM3ZDKF7Qx4c3X93Dcbz53Y1sUk241pO+pl8=,tag:YQync6GkFu+utG7JAhd03g==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcHpJNDJuVjZuQU5IMEZG
            UDMyUGcySjdKV1E0Y3JMRE9HOXRiVjBKeTBRCnFNcHgxVDRSVS9DeklFSFZBbENy
            THJxMjdKSGU1OGlFVHZFYmROdVVFSG8KLS0tICtPNnN0MkxibytyMFpxZitMNkZi
            RXRPVkxCeHpmWnlKa2VOWThFSTA3encKEKVnMgRvf3fTWdjMa1iC3f2w8eNdbxfG
            GZNkVSCnsZuHus2w5kNuN837uycmzj95xnx2htnNr5QmA+Dh2ItSNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T08:25:17Z"
    mac: ENC[AES256_GCM,data:EnKqZp2PSltP0LDL4Mjd3ijCNIkKJqi4jwRd60AFPX8h8nIUoSkrE5U/3umv2Jtd4ienwcgPXW1jZOg1XJfP0XjPCOHtXmDd+wG1VX/8Ugu18m+bpnPLJa60sLqGU8/REGeX2Xq9NaAClpIZ7LfprcjIm5CLrxNnDoL1qdre9+s=,iv:JQcvuNSFaVVgZW+3kHpEc3vXdpIHU+UXUO9Bh8SppQI=,tag:ahNcQO2O0PVaupeaYLs7Sg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
