default:
    domain: ENC[AES256_GCM,data:RCrpJHq3v9U=,iv:O8Z9ykx1dHaPcFfoB1Mk33beb86npTZXir/NLnSlqSE=,tag:ROqORo0jlPqQlCHvFJ/vXg==,type:str]
    nasIp: ENC[AES256_GCM,data:0eLda51rpUuMFA==,iv:IRXHYueQ8i3jXHQThB4mPgcxjgGCzWeXnvhXifM2IXw=,tag:Ktj4OgQ4ZI1o5Mbim1v1Cw==,type:str]
kube-prometheus-stack:
    prometheus:
        ingress:
            annotations:
                nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:P/JOXcSxJG7Sn2QfZLjFYduwCP3chSfOVdb+,iv:2WF0C3HZCJ7B6WsGKDrfgmzqlzIELRWol1DwobSlr70=,tag:DJnrPYTrrbvu+d+DY0YkxQ==,type:str]
            hosts:
                - ENC[AES256_GCM,data:FcK1Z6m2shJegiSZOT3/86h6Qw==,iv:tEkKeSNJE9ulPzYzyg8OLLN+8v9j/a4nDTEvchJN3ug=,tag:ArCdMKRCLYlTOS/RiiXqDA==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:lbnaDR6snCTMBlWig5XfvwbG6Q==,iv:oXR7SfFoe59qB8MMiTnSLJ25x8Rwj4VyfxQF24XKw78=,tag:f3HJ4ryESew5f9ulZ1wx8Q==,type:str]
    alertmanager:
        ingress:
            annotations:
                nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:44LgICgcj8z72Z2hs7YVDcszuodiwG635PG3,iv:i0bjpuoagXjwicmFk5auRtjzJk80xh6OAGJbN7HPHts=,tag:+S0lE5pt9ZLTgiQ6xubNkg==,type:str]
            hosts:
                - ENC[AES256_GCM,data:xeqaDvvKW0GpxNCm5YrjtL8wRyw5,iv:lIWWTMFcm1rzEVYtFELMq2rG3CrrbRHYRwpHu68xYxg=,tag:/2CyznnmWtzD1bX6v849rA==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:5E6Y5OGuvfddlCSEv0TNSTreo+AP,iv:47o9LCnFcBVyhkObtXZR8ok7T2Auj1V4I3rvTIYdZ1w=,tag:J/yHnzJ7Lpdpb0BNFTbCJg==,type:str]
        config:
            receivers:
                - name: ENC[AES256_GCM,data:BRgw5SIwQaw=,iv:FfKnpmPoTlbP0yblR9SsdJiI10qJ58utpDslCDrhbBk=,tag:xlBqPJxiSZxjMUVaJDBxlQ==,type:str]
                  pushover_configs:
                    - user_key: ENC[AES256_GCM,data:vWPqgcf9/MvJ6YCmbDq8gHoaJQYdsqwhFS4roCQt,iv:k837it/sh7D81pD4FwZEjnayJvZbK/Khl+NTfk+VVzc=,tag:gfT0oSzMgX5kVxcziFqnbQ==,type:str]
                      token: ENC[AES256_GCM,data:xAk9w2sgfjk4nJjStJUinXsByJTKu3fQkCOvrPWY,iv:UXQHSLKyTDT/O360b4tWsL6kFN9tsIBDioQTRqev/oA=,tag:ObY2EFrTma65MZgBv0hPmA==,type:str]
                - name: ENC[AES256_GCM,data:uUBQIcdIOUFfHCUsINo=,iv:SNU3dvV0m0Uotk/WheCT8ByDOtLY+oL9P7FE3of64HQ=,tag:nS1DiRK7vKaOQUhPpKIqxw==,type:str]
                  webhook_configs:
                    - url: ENC[AES256_GCM,data:G6vNWLW9A9Gi+mTk3+i8ZhLmwrJ2LWDfqfKijO8zGP4U+U15QwqIIhmoQ4H+IArKTjbb8c/ecY8=,iv:iVQo6tuckuql/1AVsTotupepLwIZf1cP3TH+zO9XYD8=,tag:triqZKh7ptcBfOk6VsPvrQ==,type:str]
                      send_resolved: ENC[AES256_GCM,data:udpgzOM=,iv:ulIgPd+SKKIADeVmpZm48rQKkjcg9NLlw9uID1ugR4s=,tag:QuMjU/pU9REDsPFMOdohDA==,type:bool]
                - name: ENC[AES256_GCM,data:uB3cmw==,iv:0GbyKJx2LHXSOCTOydnXWDcemA5ZBCS60AK3K5aNYN4=,tag:N3zfyMhij4yGGuiViZuwgQ==,type:str]
    kubeControllerManager:
        endpoints:
            - ENC[AES256_GCM,data:4YFM5M1wDaXQ1w==,iv:rHiuUPFoW9rxshWFKIEuDo1Ga+KgtQLLcHs3YCkLIkA=,tag:QcXUvTkYO02Ai2ItsWCLlw==,type:str]
    kubeScheduler:
        endpoints:
            - ENC[AES256_GCM,data:KIbPL3sDl4SYvA==,iv:CqrXVT27i8MwR9rnISdPJy7bWeTpWH60TxTIYGSAfww=,tag:Rho1qmkuhJ0P328pN/O1Vw==,type:str]
    kubeProxy:
        endpoints:
            - ENC[AES256_GCM,data:z1Lgsx/bgBriUQ==,iv:e4CGXwu3tlatwfV6BGCJub+aPhKlu2UhLQxoJKqRc68=,tag:XFs8W/E1ND68ALVxD7KEpA==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a0ErYVVkMUpPNEFYUEdm
            bWJjamZkbnpaUThNQ0NYQjF2WlRyeUpGb1RnCmlEMlJUTzdUVjNON1dobXdUQ1NY
            cHlSUWhMK0NFNzVlalRxZGVwQmtocjAKLS0tIGtONlRWODZPblJvLzVFWW5PMXlM
            cW1NK0duNStVNUw0TmRLRTFZZjJVRlkK4s2F53xRgoQbs3bZC4pb74v4bn4/aCeA
            PFE+NV03Dv37MK/BvgD5N32JHi0DfZPzdzR91MjuOaplN60Fiq5LQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T20:16:56Z"
    mac: ENC[AES256_GCM,data:jy49JmgfM2kHX8fbhD53/ia2dEgga2rZkBnM9Q7pRDziafDdOmm/bQO+qPv8qtFrmRSuktBCmRf/bmEGvWm0Le+STvT1IDaudqEsu29slvXlbu+Gnj6zZFzpaWm25oEwvhGu1Jd0UCipcyX99xBIvcWnfNe8kj9EvuQnuSfx7s4=,iv:ZEM5nJ6XAcke6bR5S8Qteeui9MfJDCFnsthGc9Yea1w=,tag:rsqR06NKXPjueZHKnaOYpw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
