---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dbgate-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: dbgate-secret
    template:
      data:
        PASSWORD_postgres_k8s: "{{ `{{ .postgresAdminPassword }}` }}"
  data:
    - secretKey: postgresAdminPassword
      remoteRef:
        key: "POSTGRES_ADMIN_PASSWORD"
