app-template:
    ingress:
        main:
            annotations:
                nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:/LPW1CyaMTrgvkv9o//U6DLRWoZg1JM3rhOg,iv:+yfCZ2yuIajGdLnuUDkXVXhn6KPbnrTXBu+Iwz6yx7Q=,tag:+vPAGAVw7vKHZXIMk7MLnA==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:n/HlTBzw3ec3rGOqEnsq,iv:PqgwQPMBNzUCbZKfYDK8aCLaBMzeWP17+CyfTu6EIfc=,tag:mu8zvaJ1UU9Y7C8x3XrxtA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:2g==,iv:+QiPpDSlYUPlPbr+QTtRHVn6kCWw3MTZ0eSQi7vFHBM=,tag:EApDZDmFLUsOVvVcg6oT9A==,type:str]
                      service:
                        identifier: ENC[AES256_GCM,data:g/bMQA==,iv:yEggfHFVcP8qCa5xAF+dEjhbTm0vEoe5FjlUAA9homM=,tag:nDE03pUWmP30G+0Zm3u7Pw==,type:str]
                        port: ENC[AES256_GCM,data:PDFzHQ==,iv:Ls/u7++LY4KfBIPDin9qjAZ5Qh7Er0aL3TIKjN7sAFM=,tag:unBPDZ2WgWnBfxmY+Cfmgg==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:PrQpAkfoaz+VO8L504bh,iv:MqU9pYT4kVxfg+zMwdkRloGFYyp3+Me9SmN1YF0I5oY=,tag:HBjkpKxgBZRX2QIswccK1Q==,type:str]
    persistence:
        data:
            server: ENC[AES256_GCM,data:nQs0arA22y3zCWmIRgq2eEhk,iv:Et4gyyYsLs1aFhp15boZQfofBeZPom3MRgjNz6hOUMk=,tag:j/dj/kAbWC24smJgA05k5w==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dnRtdXdhdjg0eXV2Q2Rv
            bVZhdURVclVNQ3ZWdXdDRkZQL3h5YjdoY1ZvClJOZnIxVnZiOHk2UkJCY2RQRkZY
            OCtRRnlKRmVVMldxMDF2eW5PSXo3cDQKLS0tIEJPcUdDdkFMRVFDbkdibVVBWHZP
            bzVlY0kyNnd4UjhFbUhWaFZ2TWRJY1UKYu04y/FSJQWVs0Fd/Cs2g4sag1iipoaz
            Iqs3LNoZGYb1mA4eyYceylkxvDepJE/rbMe7GBNsYIonUxU7WL5x2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T08:25:21Z"
    mac: ENC[AES256_GCM,data:LRjulMDcXGixZ5hUmh+ydusGXNgfrAsLZpuczmmBAcqt8Zak/Z3C6Dl7HgKzDd9tJDphInIvCUriC+exJuo6ZAchJQxAjW9v1ae9rmHX+lyMUdCxppQTmyaulexPBcl58G5qSxT1Y+WFt0lSy83doGHldNAjZOuFqQXBG1J7k4I=,iv:12bJ8bv/QpjjJSyMx2g8GwEfKC0hIQgMMssGtdofthI=,tag:ZM/nclFGsFe7C50nKBqZHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
