volsync:
    repository: ENC[AES256_GCM,data:y7JvR/H4FateNd+A9T3N+VFj9uXIuUxkvmKcxd5P5yFR2Cjm3EOkwA==,iv:kfP1iH1sK1IpB52C4RkoCEA8bADwBM2TeLXS09Tuu04=,tag:7h4AqX++8D0u9nruR5qI7w==,type:str]
    password: ENC[AES256_GCM,data:5hm6iah2X1L/o6SpmQrNAQ2rTM8fQh6bv/dA2ZSxwiU=,iv:M3i3ZCHnbiGXDcwwu4P37sqROtnofHuZSRwV1Y4xibU=,tag:sseUq/9j4E910x03Pk24VQ==,type:str]
    accessKey: ENC[AES256_GCM,data:d9POFP0+wLz0a4WxX11A1w==,iv:LAGiHxgEzAWb1AbkQ7PcLOzWq6kfoaY3vkKMlYFQenA=,tag:+yfiMXJR2wBBL/ay/UemAA==,type:str]
    secretKey: ENC[AES256_GCM,data:GfAHon0Qxo21jIyIVqiqu1TQqhxV3FGZZXEOjukgZ9w=,iv:EQL2xu/Cr5/2lhwwmJn4SJrN4kUETdZluGx7u3pCrOw=,tag:iRyDh1zmFsPAFFz2eTQORA==,type:str]
sabnzbd:
    apiKey: ENC[AES256_GCM,data:IRuAl/csBTJC7n3pNuFPRuyaVegtseMggT4V8jGOQn0=,iv:AbjB+dAezr4nQSXnoeRgke7RRVay6NU2jnQ5+CIPjug=,tag:6TWWolvcNH+6qBqaHz5z+w==,type:str]
    nzbKey: ENC[AES256_GCM,data:NUmTf7hCwDcvyEpgVItnVA+4Xu9iRwHdrLkNNarj1xU=,iv:yp9RmPmaSwbzm4puW5gyTOxE4iVTCTknBKNf0JingCY=,tag:TS1zC7AYWzW4LU/Rb8KkYw==,type:str]
    domain: ENC[AES256_GCM,data:mDB5zPf7O2iXJGdXRiF0zA==,iv:/EU9VaRnBfVcygqsPo4zf5KcyMNoKRMg4PpiXlZtRWM=,tag:EjF8fvept4SXxqBrIGt0Zg==,type:str]
app-template:
    ingress:
        main:
            annotations:
                nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:d78rkpRmQQCNN4BiiFoKzlbvt7qlISibehHL,iv:tukDD0y7rU6LU9C9t/jouNXFcnlT+0SuhO9FvdbDBrc=,tag:4UIVx37oxx6xNAR7SUuV4g==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:lYHxhp/LZyMnsg5/ABy6/w==,iv:mGJ4cBrO71JZ/egaKBarnwougXGeS0v8Lbn9Sp18GZc=,tag:8nZ2cW32zcJtzms03lMCnA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:2g==,iv:+QiPpDSlYUPlPbr+QTtRHVn6kCWw3MTZ0eSQi7vFHBM=,tag:EApDZDmFLUsOVvVcg6oT9A==,type:str]
                      service:
                        name: ENC[AES256_GCM,data:rFnwNw==,iv:nt9r492EOUd4FMPYq+4RvDPdEuk1MwTL0GEi3vmUH64=,tag:uQveHoFXc14iVVYCbkwHPQ==,type:str]
                        port: ENC[AES256_GCM,data:A2UaVg==,iv:Hf5Rq/ZASBzzHNY0rRrHmLRi7TDShpRxFpUKTrQ1ky0=,tag:ElHxIvl4KCYSMCL0Sr4r0w==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:BjbZuTNLm5zzz/P76ub0nQ==,iv:kRYx7TNWzx3a2MykuXqVcGJIavbE0AdduV8K4WMUrp4=,tag:GoGON7EocgxYaLyVZlpdyw==,type:str]
    persistence:
        data:
            server: ENC[AES256_GCM,data:H84oFl3c4+twUGWSB0vPdl/F,iv:aRjMn99rnCAfZ0bhAA4fs0JUrVaE/8wMzKMqNg46sag=,tag:Y9pB7XwNlCvtCSaco3o+Tg==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dnRtdXdhdjg0eXV2Q2Rv
            bVZhdURVclVNQ3ZWdXdDRkZQL3h5YjdoY1ZvClJOZnIxVnZiOHk2UkJCY2RQRkZY
            OCtRRnlKRmVVMldxMDF2eW5PSXo3cDQKLS0tIEJPcUdDdkFMRVFDbkdibVVBWHZP
            bzVlY0kyNnd4UjhFbUhWaFZ2TWRJY1UKYu04y/FSJQWVs0Fd/Cs2g4sag1iipoaz
            Iqs3LNoZGYb1mA4eyYceylkxvDepJE/rbMe7GBNsYIonUxU7WL5x2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T08:22:59Z"
    mac: ENC[AES256_GCM,data:IQ7B1Q/sQ1fxAeNxChKgLU852KVqb7FZuVN/ThgTY9N0uxMbOlUJpqrz3UD9WIlRiN3gvcDYTibrH1LJZOj5K1jFY7dNW7wtRA5o/rxpUL8C+IA9TH+ODfBv0LkfY/bm+9HzKlpD2ZabxOMoWBudmjsltju/1/aquEhJeAw9Fys=,iv:s4LxIVt3tTWu32m4kIlvwkUjv8uR4/fzengWw2w/YBU=,tag:POukH/IXQEg7LQnBOP5nVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
