volsync:
    repository: ENC[AES256_GCM,data:FEwL6QMGvm/LROL+Eq2tzsxwUkYX7Mbg1FB5rwlsab7SxIWi0FA6SA==,iv:Q8nufRZA2CZGZ3O3vqs8G1jrDngPyvlTwButnkKLtyA=,tag:uZ5rRji6X/edsQmGeC/TYw==,type:str]
    password: ENC[AES256_GCM,data:lCDorZyCJf3qkF0u+2y6hCfCIo9c8+/mSBXrnKj3hyM=,iv:k1hd4MUkI7OgiecmLOPglJgi6f9wfuq4kyrNz40HxkE=,tag:B4nyiPs9lbCi3pn6rIaKBw==,type:str]
    accessKey: ENC[AES256_GCM,data:riWCprnI9VPyKFpKssn7Jw==,iv:F0p7Zg96jcfNvYRmBQn9tjeUr2L5aARwMddrJlTS1OU=,tag:VozEn6sczXJocHSrT2V7ZA==,type:str]
    secretKey: ENC[AES256_GCM,data:syW+KZ8SmiyzfdKn7kYp1wd9miboDACt68O51InHHmo=,iv:jxmAOgXTihn3S4CI0hFZy9+5Kh0lu+UvUN+s9KOGM00=,tag:zZNeTrGncXscs06kgGTd6A==,type:str]
app-template:
    service:
        bt:
            annotations:
                io.cilium/lb-ipam-ips: ENC[AES256_GCM,data:ZUPqDjvb4I7OCKY=,iv:yh/qdajnbudWolqdtVj4pP648hfk6BzjDCTwzWwDDyg=,tag:703dT9Ci3dmyBQ5veorNRA==,type:str]
    ingress:
        main:
            annotations:
                nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:ULuzZaEyS+uOvO1FKwCJ4cI0ixjdYJsPxuV4,iv:UIFkTnefY3ThSVPVrikddxgrY0Km1UMc/IQHYGLO7YE=,tag:uzpne6s3Ztul6rbekX3rtA==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:d7yCi56rB2nS6A5cN/dqFONwxSU=,iv:jDQPuGR+h/BnzfBlU12wtVBZLBJ6cAkdEifHZFwQWK0=,tag:Zxpqec/IrNjO+3ElASNULA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:2g==,iv:+QiPpDSlYUPlPbr+QTtRHVn6kCWw3MTZ0eSQi7vFHBM=,tag:EApDZDmFLUsOVvVcg6oT9A==,type:str]
                      service:
                        name: ENC[AES256_GCM,data:kps6hg==,iv:Y5rXeBw59EZkat5SLlByOPa8qcWnNYvht68PGira0zQ=,tag:CBX7uRF2SYekjBENceliiQ==,type:str]
                        port: ENC[AES256_GCM,data:vfBkjw==,iv:sf5SO/iainR8PYXNSdMOQDRdSQisOHXViQpT3pVpI2I=,tag:zQwqaEZ+qydFMx4dGmT/Ew==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:3bVn3jOcAA5MBsDc0XbCBmXTM58=,iv:b+geKsQ+ET0RpoJkEeP7VNimC/yy0xRSg7CknetbfS0=,tag:QkGWN36dx3oTxNXO3YaIFA==,type:str]
    persistence:
        data:
            server: ENC[AES256_GCM,data:zxffFB3cX04xTw6SXbVi6Kw0,iv:osKvNEoo1qQi0wssPRz1cMIehnAar1D35yfzf8LPH4Y=,tag:y2TBvUruU1wFqArmxoVxfw==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dnRtdXdhdjg0eXV2Q2Rv
            bVZhdURVclVNQ3ZWdXdDRkZQL3h5YjdoY1ZvClJOZnIxVnZiOHk2UkJCY2RQRkZY
            OCtRRnlKRmVVMldxMDF2eW5PSXo3cDQKLS0tIEJPcUdDdkFMRVFDbkdibVVBWHZP
            bzVlY0kyNnd4UjhFbUhWaFZ2TWRJY1UKYu04y/FSJQWVs0Fd/Cs2g4sag1iipoaz
            Iqs3LNoZGYb1mA4eyYceylkxvDepJE/rbMe7GBNsYIonUxU7WL5x2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T08:22:18Z"
    mac: ENC[AES256_GCM,data:0jpZnlzHna6KYEle1Xa0DRfAzu1SHX1bY9wm4uit6yorDTDBotZ7Y6IZ87zQSEL6uNcZpksYy4/+BCjlu3TwFlWYOY25vfgpEkimcIRqAUzD1PVbhavWHmruVP05RcrzPrHOZmzJ7dOLUNDALTzEYI30RdZ/OCyLwoKNJ12FTSI=,iv:vTIxT58sQ83jCP9J7uOpzmakxay2bQyTfwO1nBrOSGk=,tag:X0JuZuq50wv0SRX5n9aldg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
