apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tinyauth-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: tinyauth-secret
    template:
      data:
        PROVIDERS_POCKETID_CLIENT_SECRET: "{{ `{{ .clientSecret }}` }}"
  data:
  - secretKey: clientSecret
    remoteRef:
      key: "TINYAUTH_OIDC_CLIENT_SECRET"
