apiVersion: v1
kind: Secret
metadata:
  name: tinyauth-secret
type: Opaque
stringData:
  APP_URL: "https://{{ .Values.tinyauth.appUrl }}"
  PROVIDERS_POCKETID_CLIENT_ID: tinyauth
  PROVIDERS_POCKETID_CLIENT_SECRET: "{{ .Values.tinyauth.oidc.clientSecret }}"
  PROVIDERS_POCKETID_AUTH_URL: "https://{{ .Values.tinyauth.oidc.domain }}/authorize"
  PROVIDERS_POCKETID_TOKEN_URL: "https://{{ .Values.tinyauth.oidc.domain }}/api/oidc/token"
  PROVIDERS_POCKETID_USER_INFO_URL: "https://{{ .Values.tinyauth.oidc.domain }}/api/oidc/userinfo"
  PROVIDERS_POCKETID_REDIRECT_URL: "https://{{ .Values.tinyauth.appUrl }}/api/oauth/callback/pocketid"
  PROVIDERS_POCKETID_SCOPES: openid email profile groups
  PROVIDERS_POCKETID_NAME: Pocket ID
  # OAUTH_AUTO_REDIRECT: "pocketid"
