---
apiVersion: v1
kind: Secret
metadata:
  name: tinyauth-restic-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: '{{ .Values.volsync.repository }}/tinyauth'
  RESTIC_PASSWORD: '{{ .Values.volsync.password }}'
  AWS_ACCESS_KEY_ID: '{{ .Values.volsync.accessKey }}'
  AWS_SECRET_ACCESS_KEY: '{{ .Values.volsync.secretKey }}'
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: tinyauth
spec:
  sourcePVC: tinyauth
  trigger:
    schedule: "0 0 * * *"
  restic:
    copyMethod: Clone
    pruneIntervalDays: 10
    repository: tinyauth-restic-secret
    storageClassName: local-hostpath
    volumeSnapshotClassName: local-hostpath
    cacheCapacity: 2Gi
    moverSecurityContext:
      runAsUser: 1028
      runAsGroup: 100
      fsGroup: 100
    retain:
      daily: 10
      within: 3d
