app-template:
    ingress:
        main:
            annotations:
                nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:+3rfnb3c+6nNlWiGoLrodyCAfthK5VVV5DZa,iv:U2OWZueeRNNGSOc0RLZLaVdHwu999F2jwOJVKrA+R6s=,tag:23/HpW4fD7l0vbIPnCIKGg==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:9NFAUroc7wIrAGMvtDQ=,iv:98St4JGrEQbWtDQfejw/h+4u4T7yWqWnAHDaJCFvIyQ=,tag:v7rU93bY5vNWU+M2n4TK7Q==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:lA==,iv:r+T937WlluzX5FZ6fm91d0c+ZjOyn6mbZ0y6yGJXG9g=,tag:04mNQ22PJFRvaXGg99/Isw==,type:str]
                      service:
                        name: ENC[AES256_GCM,data:eVWB9Q==,iv:2ExuSXMu6Amz/I6pNBw+nYmWR0QFC27VZkLCXVx4Wds=,tag:NN2WgiijV7/y91Lrgk05eA==,type:str]
                        port: ENC[AES256_GCM,data:JVuRUw==,iv:wSZNmvE4cgZwhvyVe/zuUM8Zdzy8H96xPb6KNLqur4E=,tag:f6f+h+HrDuUWshMCg++Rjw==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:IQ+fxQFaCvhT1t59V74=,iv:gJ1HFOulyZbPxammWewmCi6ZBIdgNfWO3iKOD0TGiSA=,tag:jTPHwRgnx7vMlmq0/3yh2A==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVytlWTlLMWVocHVCNTdQ
            NzVUMEZaU1pBTEd2ZHN3RWx0d1QrVWVLUTBBCmlpY2xVTGc1VGE2ZlMrMFhXUTFw
            SjVienRVWDNOdmFzdmxVK0RSbzdNQ2sKLS0tIGxKTjBBcEFRbk56SXNqUlptT3h2
            cURMTE9LdXp3NGRGVUpnRGwyeWxBK0EKmBpcJSFclkgqXP2iO5Zmsf/rHQaOAvI/
            P15HZUDvDhvdgBrF/y3uXc9Ur317TQiKSEw9yj33B/cl7NKBEFOFjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T08:25:43Z"
    mac: ENC[AES256_GCM,data:p9QhYu7S5uFBjw5sclxjMTyFB3/d42mjbWRuiNrmXT24uZdBT6qJwBN569A67pjC4syZbP68rBiPT1jLEq5UfsAyGsM+M6+QQijWQHLVVyj3XbkRfMrHeYCIIds6VqP31IiZCHCuSS4LhgJuVqhDLOOIi+adG/azMuPbWvUtNgY=,iv:cdVjYIQh/Uja4bvGPL5Is/tEX9MWsVqUUcOdbUmZe0Y=,tag:IpA7SmCubB3wfl1rQm9rcg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
