volsync:
    repository: ENC[AES256_GCM,data:Oz8fcfUHLMjnfBM5oYp5VuM5WVc5422Ylful+g791V96RxxFppjx3w==,iv:SqTxemLmIh7ulOpwh5xcVt7JhoupL14TjfrGbxuS8es=,tag:ZGvCPIPIf4RNSuGaaAh7Aw==,type:str]
    password: ENC[AES256_GCM,data:C4rO8opM2WcOsIpT7vmTU+mWy3aPSWGk4G2YeujhljE=,iv:tP+EaHZuMCyoIEKokj3IYksshVpUDOvR/Lvh1sC7Fok=,tag:Ql2q5Zz/N5DfzgIchKt41g==,type:str]
    accessKey: ENC[AES256_GCM,data:AKVUvvqbhJ9BY5yxZru0Dg==,iv:GTQ0Vf7REd5ugIb1y/HfldUq6kyGFowAzXljkoj93Rc=,tag:N58G5J1lK91IfDIyYawaVw==,type:str]
    secretKey: ENC[AES256_GCM,data:00j4Ap5GwaQGln4Xy7H/vnZicPEJeWHXNmHthyPyURw=,iv:Jx2AH/yarHOXyhmX9qyUF8rJSSfkMedL9MdwayjLaLA=,tag:BLlluYlmjeSz0cGCb354cg==,type:str]
pushover:
    token: ENC[AES256_GCM,data:QBAns8nVuxddBrn59VtIk9+fA/abjBLWh/lbIj+y,iv:jdDSyMwZ9xrn/tuDY00+DjiURGbh03BhAGP2JAwD9Hw=,tag:/WN6oKa9yeV6w/eoIi7yCw==,type:str]
    user: ENC[AES256_GCM,data:QVTfoClQlOYGxliIqOR3NcqAUSnCJNpN1xS19Z73,iv:d+HLx+GAR12yKqy3OugKIAVU2WEmUvnPQbyoMWd/jvY=,tag:wDkvyoxdCKFCgIZOkDR84w==,type:str]
paperless:
    adminUser: ENC[AES256_GCM,data:AV0vfg==,iv:j2ztagQXWBtZmE2eSdf7NRH5gTi7NGD8crCOIb36Dtg=,tag:qeBYPw/AKWwYZlX9NWtrpA==,type:str]
    adminPassword: ENC[AES256_GCM,data:4IBsoNSNwRiorZveP5avRGFf5R3xPbJVqH3RKCy6AIk=,iv:OyWieUIiEo9BL6+o0brElz4rV8oBkIWgqcSQ6qSUjUU=,tag:OvXS+bZ6lxsHGgpaSSpLLQ==,type:str]
    secretKey: ENC[AES256_GCM,data:i+5DteAhR5eDL9Lb4EWR71GpmPR76CrQKOHuwZ6CCKE=,iv:Kwf8gad1gzwXmeLuiSoc9OR9chSipjgOe1TJ6ZJBP+8=,tag:DiurcR/4DUJvknOU5AjJhg==,type:str]
    url: ENC[AES256_GCM,data:tfS7+Xtyo6uk0scZM9ey/tuwhoGrrkKJts0=,iv:uTXNoKwGRgXwBpHfb0f4HzDlRq85H/h6dib4JD09x4s=,tag:9lGZdT0kSHZmYj6K3vJ3pA==,type:str]
app-template:
    ingress:
        main:
            annotations:
                nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:9bJunh80nTtPrtbuuT+b8yYNVx9yecndYnp1R1JqZQNvoUuyKOqbeg==,iv:2P2mHxlWxNqjlA2CK9uU7FaEJ5GFfA0F5HH49sNYgZQ=,tag:TuTJakJNE9+2wblBOZxZYw==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:Bek9BiRjYwYbcl/Ym3PImAHW,iv:GoEky8NhwdRBwPo4grkXUZEOCF2IPQ2YSnY+yyAXTTw=,tag:wncS+WucR10loX6h9d16vg==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:2g==,iv:+QiPpDSlYUPlPbr+QTtRHVn6kCWw3MTZ0eSQi7vFHBM=,tag:EApDZDmFLUsOVvVcg6oT9A==,type:str]
                      service:
                        name: ENC[AES256_GCM,data:AKnYlQ==,iv:vv6NWaYkRTkICRSsPBj2d49c4tpgTjCSEtw7VcLb5nQ=,tag:6C+sFT/gMMmFnE65GUMvWA==,type:str]
                        port: ENC[AES256_GCM,data:i/29rQ==,iv:k3x5HsWGFLhi2zpSotEOvd3d0FcHjku876mOLRDibug=,tag:YOEMHPMjni/bg8MYTTn9pA==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:TOlWSRpR9k7/JVWRUFc825W/,iv:tgW71NR80tGeGTkuHo+iqBqdpXgTAN4rqFSmxAF7STI=,tag:yO9+yKHXiq2JfK9Cz8tf3w==,type:str]
    persistence:
        media:
            server: ENC[AES256_GCM,data:M6e93WTiOerk7oo1GAyatdnJ,iv:gJpqEQDGsF+PQqyzRBT8TVJ1Ui0WIka82JR3lWH/4f0=,tag:1pgI1M7c26TG5pbKOjyXPg==,type:str]
        inbox:
            server: ENC[AES256_GCM,data:7AwigZsEN4S+ioq97ZQ52hV5,iv:0hVLodOVyVlQqHlzaj2d6N5X+GUZYj3fAmnPN6AhVew=,tag:71B2b7LSrMvZMtChJXd4QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dnRtdXdhdjg0eXV2Q2Rv
            bVZhdURVclVNQ3ZWdXdDRkZQL3h5YjdoY1ZvClJOZnIxVnZiOHk2UkJCY2RQRkZY
            OCtRRnlKRmVVMldxMDF2eW5PSXo3cDQKLS0tIEJPcUdDdkFMRVFDbkdibVVBWHZP
            bzVlY0kyNnd4UjhFbUhWaFZ2TWRJY1UKYu04y/FSJQWVs0Fd/Cs2g4sag1iipoaz
            Iqs3LNoZGYb1mA4eyYceylkxvDepJE/rbMe7GBNsYIonUxU7WL5x2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-04T14:49:02Z"
    mac: ENC[AES256_GCM,data:4u4Rzyj3bmBHsc4soVRJbbXCuZKYHF7EEAcg3AWMkOHpJDkzCqxyowjLVd+MVdepaZBptRmuWcpDv2DY9Sf+CY1JHltviAkTua0AHU7S9SiT+A8MIDOHc1Un8UxStELHFFo4ErOz5iwmTUJqDNgQroxEGwq2QoFDiFHGGUdN0sM=,iv:K75PTvyUFCRoBLntmA8020VcENBhHzPvJJzLrMhk6hI=,tag:SH/T2sOVkNXH0lDWDgyk1Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
