apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-secret-temp
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  data:
  - secretKey: APP_URL
    remoteRef:
      key: "POCKETID_APP_URL"
  - secretKey: ENCRYPTION_KEY
    remoteRef:
      key: "POCKETID_ENCRYPTION_KEY"
