apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-secret
type: Opaque
stringData:
  APP_URL: "https://{{ .Values.pocketId.appUrl }}"
  ENCRYPTION_KEY: "{{ .Values.pocketId.encryptionKey }}"
  SMTP_HOST: "{{ .Values.pocketId.smtp.host }}"
  SMTP_PORT: "{{ .Values.pocketId.smtp.port }}"
  SMTP_USER: "{{ .Values.pocketId.smtp.user }}"
  SMTP_PASSWORD: "{{ .Values.pocketId.smtp.password }}"
  SMTP_FROM: "{{ .Values.pocketId.smtp.from }}"
