default:
    target: ENC[AES256_GCM,data:Ko07ZPj9/IlHtx9v38bxC14=,iv:WC1aztVRVWrUZOmGu5Gm7/a35d0heD5b3PrRGumaZrA=,tag:gnZQKEMvlpMMBz9KVm69HA==,type:str]
    domain: ENC[AES256_GCM,data:bqJCDaxtPbE=,iv:jeVSWqPbcgwxxlVqYbpgjapOUEviAwpPgu69dKdCRXI=,tag:8lq20MbbA9lsVDUdnSGLXg==,type:str]
photos:
    port: ENC[AES256_GCM,data:ivBUgA==,iv:b46UZi/UOekcyD/IwnZ+Dp9J57d1MJBc9iaLK039Lzw=,tag:dmW6JbE6ZSrfAvaw6ixryg==,type:int]
    hostname: ENC[AES256_GCM,data:SUcrhx9PGjrJsJQ2rr8=,iv:zrlHzXfiBozOkaSjWtoovBqGaniXt9VCortwZ3o/Sik=,tag:u/haqQJ0Zc/ydaLkjk5RIA==,type:str]
drive:
    port: ENC[AES256_GCM,data:HhLthw==,iv:AlPXlL/VUe4Pqd+MBt09HVeIl5tHvqnNeChpo6CP2oI=,tag:+xZYRuAynBTRfiuN58Oy7w==,type:int]
    hostname: ENC[AES256_GCM,data:S7X6W631ZKxLKEc1X44=,iv:oFCr8M+TiPD589asfPt/GzVu1K5bx3msj9tIiXPYT8w=,tag:D/vxiBZhw+I3A983bnffng==,type:str]
nodeExporter:
    pi:
        port: ENC[AES256_GCM,data:UHIlOw==,iv:JC6wTQCq87SzCLQC1M7z3VK1SOWGnERNXWViIWqbEOY=,tag:v99KeXHMlTMLiYmC/9wOLA==,type:int]
        ip: ENC[AES256_GCM,data:U5TGokrWW1J8Jw==,iv:/ImxVZydPZvOd9QkLSNIfoIGd57EFgUr2fGSzthR4pk=,tag:Y+Fz/9RXSeseAzefxjxmkg==,type:str]
    nas:
        port: ENC[AES256_GCM,data:k94j6w==,iv:zqh7sTxCXygZpd9dnRmmCE0Ro8dcZQZ9nnT+TXCzXVw=,tag:RKX0SGA5NF3GGv40+l3EbA==,type:int]
        ip: ENC[AES256_GCM,data:U+CHyYHRNQspew==,iv:4aO2eKsBXJQ71voBEDKwFjyY60M3LfhFYLgipjl594o=,tag:DKSe21GtzEaU97ZOYGZk2A==,type:str]
minio:
    ip: ENC[AES256_GCM,data:1VOUp3zILdOqiQ==,iv:LfJ2xoI9VwfC+CeDMNK+zHfdjG1VFFGqsITcZ5YYctA=,tag:T0QPH2vnpEwR3MTEyDF41w==,type:str]
dns:
    ip: ENC[AES256_GCM,data:H+iUmZjDd/yltg==,iv:VDvjQ87z5Q20LsdCbGMIUtcfkW1/o0qwZJMs+aidSAM=,tag:GPksjNmGaD+SDpDbhKB9YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVkF6Rkd4ZUR0aGRFTGtz
            cTkzR0hETW9XelEyNC95di9sTFZUa0xHN0I4CjRhNVZrMjBENk1jWFpMMitXR215
            TGNEL0o4NFFqcDJFYjBIcGkrRmNLOUkKLS0tIEFMK0duRnhscXNaaUpHVlF4SzM3
            ZEoyUmFJbGJaSVpTWlJud0Rucnhab28KTuYeoL4GuItemr99JgTZrej7zbh0i9DN
            e00b/BCRr+R+Btx/ocXHXP5hTNliFFgdT7DmhhmhwySlO6xVNfnsUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-04T10:06:20Z"
    mac: ENC[AES256_GCM,data:PKWvzL7nycE6F8igdcGrOPd8S7iW+Qzd16RUOuYhSsSM/kj6FYZcEYE2lQhAEpDfq3n+UokcCKruBlo0/b7OReSj8kaE95rGDebgfgYHH3lkVlMisEu5naMDYyL/A/T1puwIg2GBcrhF1VCr81HDJwgToQ+KBxVZAtasOW4l2vo=,iv:MVQtlcnI/7eE/Wdz1EysrrpgIEU+g4nCsxrXbx4nNTc=,tag:qGf4ZbpfXn0dwu6jhF7zkg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
