apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
data:
  users.yaml: |-
    users:
      mfin:
        disabled: false
        displayname: 'Matjaž Finžgar'
        password: '{{ .Values.authelia.user.password }}'
        email: '{{ .Values.authelia.user.email }}'
        groups:
          - 'admins'
