---
apiVersion: v1
kind: Secret
metadata:
  name: audiobookshelf-restic-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: '{{ .Values.volsync.repository }}/audiobookshelf'
  RESTIC_PASSWORD: '{{ .Values.volsync.password }}'
  AWS_ACCESS_KEY_ID: '{{ .Values.volsync.accessKey }}'
  AWS_SECRET_ACCESS_KEY: '{{ .Values.volsync.secretKey }}'
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: audiobookshelf
spec:
  sourcePVC: audiobookshelf
  trigger:
    schedule: "0 0 * * *"
  restic:
    copyMethod: Clone
    pruneIntervalDays: 10
    repository: audiobookshelf-restic-secret
    storageClassName: local-hostpath
    volumeSnapshotClassName: local-hostpath
    cacheCapacity: 2Gi
    retain:
      daily: 10
      within: 3d
