---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: qui-secret
    template:
      data:
        QUI__SESSION_SECRET: "{{ `{{ .sessionSecret }}` }}"
  data:
    - secretKey: sessionSecret
      remoteRef:
        key: "QUI_SESSION_SECRET"
