volsync:
    repository: ENC[AES256_GCM,data:chnuRKzn1dKtiMo3BoAn/Ec2hbgEZdMvQX2Wg2aUtpNhCYFHqPcG6Q==,iv:SVMZ8TyLcl0H8FTx5uGvL2eGWpFXm3rlzyL/W9BBg3M=,tag:xhXv3pQo33qtgY2DqHCqwg==,type:str]
    password: ENC[AES256_GCM,data:JAw/GJ6Y1sMuuyjZqNQmE00NaW6suvTdrW6cDlqx1nw=,iv:sWvuijTStdtr6DEQviGGFSSoNtaGtNySsdRccpiZpRw=,tag:bVxFxco/g9FJq/YYsZik3g==,type:str]
    accessKey: ENC[AES256_GCM,data:WJ1fBvVxGjJcLPlM+edC6Q==,iv:0cvjlnylv7TzuZZighdIg0C3NxEgQ3d1LI6RnwIog9Q=,tag:aVWbndLwgFw6i1UsFl4Rhw==,type:str]
    secretKey: ENC[AES256_GCM,data:cGSNRk6LCZ4wADRI63QT/sf2MejMx5wglMQyeJoIjRQ=,iv:xkzvSbZkssQ7CkfjP2/toDhiNMUrB4JL2u6pEcDgiK0=,tag:Ig03aKdfiS1H/709FDLb9g==,type:str]
minio:
    endpoint: ENC[AES256_GCM,data:5/2P6dK/+O4SILtX7Y5Mq64Tqg==,iv:KlUl5quH22mX4QyiJRfGDf0AdYzBU+iwAheyfGD2ieA=,tag:sGC7+Xs+2KoeEl7hUi1kjw==,type:str]
    bucket: ENC[AES256_GCM,data:dN1NIyUCWTIg2A==,iv:DNakos8N0TZGXlsxVP6RVFTGTeW+A9FARODwTKrpXnw=,tag:91b4CYF7mgP4CIQsVFoATQ==,type:str]
    accessKey: ENC[AES256_GCM,data:UN0rVKXkxq1IDahiYQoHYw==,iv:rgW8wRim2WbMPRt4/hFQOf0nJiUE3ByqRmug1PjMB5c=,tag:RVUXmgIORFekS8m7XVejWA==,type:str]
    secretKey: ENC[AES256_GCM,data:Pp2UxGvZPkcydffzNPCwI7jf7kJMMoHLe9UB4T2/xyU=,iv:UucSiK/HlbC3tqmff4X4BRJdK+CmARj65xu14Dm+k/Y=,tag:Yzs4+6GIHUqAgMQpMcehnQ==,type:str]
nocodb:
    jwtSecret: ENC[AES256_GCM,data:d9JpalFWPndUeVi7Z3WX35XBrZ/iQ4rPm5h9og==,iv:hncrS5pboClq7oXYc6p1lXRH0g2OVuGCLF4ZG/Vx358=,tag:3aOEx6JUKucPntp3S/VHsA==,type:str]
    domain: ENC[AES256_GCM,data:gmgMYVIzDyzfDj7d20kG,iv:RnLp/gTwTdi+0G3KfB9tGfy7cYbY+J0RSGwpDVk3wcA=,tag:goJoSCL4Zi2NafYufAqIvA==,type:str]
    admin:
        email: ENC[AES256_GCM,data:qaCSRfxkBRvUfFU2K55SUIA=,iv:biHrkO8HTm7UiHDIP1yroZnC3x8RJXLRkvE1RNf2IY0=,tag:1ILbmDgzZUMefPnmsfE/BA==,type:str]
        password: ENC[AES256_GCM,data:WwLYI06L3gU/tsfL1dvWHIxA+l4wIcNtneybactL2I0PoA==,iv:PYybIoieONBKhajyeaf5yfwmvT40HCza7S4hCAY+YpA=,tag:2pllTHMSYV99xpIPla9BlQ==,type:str]
    postgres:
        user: ENC[AES256_GCM,data:5yOdxfNl,iv:PYyrLWPaVq7E+L24azl7ZvVJETNw8KN5lElCWG5IdiA=,tag:AT6PzqEGrLaQ5nv9BAJDfw==,type:str]
        password: ENC[AES256_GCM,data:S2iUaN6ZPA2V9pP4tnRWgBZdHxM=,iv:7puiC0Zgv84X3CWsn8P91frnbmQvj0h38nXW+co0h5U=,tag:wD7reefy0rymhmpLXWSapQ==,type:str]
        superPassword: ENC[AES256_GCM,data:U98F7ewe2S/YyHk0my+UKXUEotY=,iv:+zjo8uWUQRpMv8UWAJ5/caYeejbaH+TJLOe2oG2902w=,tag:Lrkvsdms2uBkb4XnBbF3xw==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNndtUk52UWVEd1JmdTdp
            VmdIUHUyMXdpN2wwQjJ3TGxvQklvanBmNUc0CkgvRTdxUWdSYmF4UTZIL1d1TnRY
            QnJmWHpnNXRzdU1qMzZIcWhSeGYyQUEKLS0tIHBEYUx6OUFsSFh3WkVLSXFjWVZ1
            bnJDdHY5TmduejBkTXd4SFhxd3FlRE0KHgljYmngh+ny44ayLO2znvMIlVjfpOv4
            N7L60KVTErsgepgjRqYTdHzISBUH8UGJoiH6XQ2p+ma9dA+SAF0Z2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T10:20:52Z"
    mac: ENC[AES256_GCM,data:3JlOX7oyUITa1b0hnw+uzm1uHcA+i3Rg/iWLpw0iuG75+SbJi5y20xmW5PUOLDnKS2HRqteAA9Q8ZrJN0vJFl/G/CIiV2qB+AiGfy64tlF8EwDVaq7tSvPjWLDMLS808jTddDdb698TLIl3P2UqMw8H5P2R9phFfGkpbdHNoGjY=,iv:/rEqk9wnd9bOkLTa5Osw9ngEW/93w+iu5qEjgPd5NwI=,tag:m3/dhaqF1jBk6ctf4hgjpQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
