---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: slskd-secret
    template:
      data:
        SLSKD_SLSK_USERNAME: "{{ `{{ .username }}` }}"
        SLSKD_SLSK_PASSWORD: "{{ `{{ .password }}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: "SLSKD_SLSK_USERNAME"
    - secretKey: password
      remoteRef:
        key: "SLSKD_SLSK_PASSWORD"
