apiVersion: v2
name: redis
version: 0.0.0
dependencies:
  - name: app-template
    alias: redis-paperless
    version: 2.4.0
    repository: https://bjw-s.github.io/helm-charts
  - name: app-template
    alias: redis-authentik
    version: 2.4.0
    repository: https://bjw-s.github.io/helm-charts
