volsync:
    repository: ENC[AES256_GCM,data:vBOk/YEkpNCm2swxNyqqryE32AQWnvhFWHt6j70Zld5Oz/TAd/irDg==,iv:1B/n31Aa8tkmxSY9iqguDZLizgaPLc0KqYo+DaDtkBU=,tag:Fd26xzkhiLHs7CcJDtujzQ==,type:str]
    password: ENC[AES256_GCM,data:+sBg+FR9RGCWntO8z7WZJ/8eEe5vqCjwim9LxtKodpo=,iv:ZI3/x/0sUPwwjWHMdzDbyd7GJGObmZ5MNt9L1JJ7yT4=,tag:egj6wV4gIQUDU8R8w3BGVQ==,type:str]
    accessKey: ENC[AES256_GCM,data:iypMyMOAfoxG5L977ZtOpg==,iv:siJMxQJ5gjfk54MKQi09LcQ395KxWl+19Mmdl45DFj8=,tag:n7p/1vaA0BK62UqY/6r6Fg==,type:str]
    secretKey: ENC[AES256_GCM,data:hxV35vLBuLggiiWWIkaqZ0wRbPLdvoEyX7HQrhBUu1g=,iv:UEnyJlON3Hp3b5SDAcI8Q4/W2r4B+aZ0XXj5lKpJz00=,tag:L64Vx3Rtb+nHpexEZzkbWw==,type:str]
minio:
    endpoint: ENC[AES256_GCM,data:H3ElodvMUSjyxIkAeKYZUJSC0A==,iv:g4dpRb9oZE0GhSjTNuivHfzyKEB2D9LcIi3t4P24sUE=,tag:buIhFxeWjWLCF78kyraPMQ==,type:str]
    bucket: ENC[AES256_GCM,data:dBg1J5F4qKu1QA==,iv:mRLYbvh3jX+3ldjeVb3KGuyrpxHpbnEzVFjzGTjtCYs=,tag:KtS1i/4R9iZ5WoiTcQpyQw==,type:str]
    accessKey: ENC[AES256_GCM,data:K0JLPVduzpSWlnfLvk+2GA==,iv:BaVkK96VTzbQWn8GtX3Hn2NUkzq8cEOEXdsWtjoYKYc=,tag:3OK9mQbZFFpvxZfQzpUcaQ==,type:str]
    secretKey: ENC[AES256_GCM,data:OJPdi4m9t9HXjHiXI08Dvjquz5Nyca2uuy4erw9ZX7c=,iv:eTGBWQWymsbi6jCDwNd5GWzFpKGONaYpfauLp3P9Jlc=,tag:kby0xnAQ7brmV/e3JVkEvQ==,type:str]
n8n:
    url: ENC[AES256_GCM,data:jzFWGlsKUY2qCfsE,iv:lkMu2uy8wrcluCkkIW270dWDCz8oXmu1W9ZlYrg1OW8=,tag:eUADsUCPojSG+omh46B1eg==,type:str]
    externalUrl: ENC[AES256_GCM,data:4/HfzxMO28mPcwi5UOhg1k0=,iv:yvD+Y8vJSymKs+PdS+ntbgPZ8WAaHV6a3kiNf7ERk9A=,tag:SoKXAixkvsNpbgOGVo9/+w==,type:str]
    ingressTarget: ENC[AES256_GCM,data:FwmSiMrfcmIng9BiM3AfnH8=,iv:HkejdZn7LPHfXkC5T8fH0EckkiYzEeu4xCAeaCMbv1E=,tag:LAEve/j0v/DHEajjtk3nhQ==,type:str]
    encryptionKey: ENC[AES256_GCM,data:fj8zDprjhIJQNrsF+s36xn6w9A==,iv:pOE3K3mysqK88bG/1CupYxS/71JN5DhFFL/EFWUZ5MY=,tag:ZEnYNTxe7TI3DNcgPK56ZA==,type:str]
    smtp:
        host: ENC[AES256_GCM,data:90LwmIkK7npvf6wTFbf/TTs=,iv:667V/X/Bt/7wdAIRcupb9W1JcuMOfLPFpa4W1RPlA3w=,tag:FwdEMdRzGZPnaHEaJbmn0A==,type:str]
        user: ENC[AES256_GCM,data:IhhtasBl81O2O8Nqzqz3Taw=,iv:XfLqK5xVRfwqF/8T6Wr3mlm5kSvkAdoNbUE1Mkkssgs=,tag:Y72N/vdMIB7GklNETKXRJw==,type:str]
        password: ENC[AES256_GCM,data:nOLcCjHliXgxx6atYqAiBg==,iv:OdEioGBzixex3JY3EaBjmso7f/fEUaviHFrEF9k8/WM=,tag:tohWXp85qFRd1O4AyvDd+A==,type:str]
        sender: ENC[AES256_GCM,data:eY/ArB+GZ/fyaS4m,iv:NFSlZdtB/5hSz8pc80SoKIFDHJBHWe15hKxhDesSwGY=,tag:MM8RegDxrT2U1LabtV88kw==,type:str]
    postgres:
        user: ENC[AES256_GCM,data:1VTQ,iv:VAQg25uAdoCd0Ub7JxnxVwUg59UXblYgHP2os8aqZNo=,tag:4ked5ZG0EOxmboULjxnd0A==,type:str]
        password: ENC[AES256_GCM,data:v5CrlirrUq+h141ei75eMnOgsBs=,iv:bOjpK1ePMNwHoYc63Ln2BTmfLiEeOsNjZvgMyOeafqM=,tag:QDnv72yaF/qZrQX57P8Y7A==,type:str]
        superPassword: ENC[AES256_GCM,data:Xg+08zTO674gFJm5l16QyYoR6B8=,iv:PeFp6q6Ixzz3r9MaAG1k4NB0G6IOtMQiDugJcOomRGY=,tag:NSgJem2m/b7SE0WmxNOpjw==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMWplT2sraWFleGNuOVcy
            Wi93eFE1OWJNOFcyWFd2bU8wWm5HcS9OdFVZCllFZWdSUDhUU3Znem9sMmc3andP
            MHdHcDJCVThQekh1SkdVTnVsOTNOQ1kKLS0tIFBYemNBaUpjUlhaeGNBYktSaHk4
            NzNPWDVaZitaVDZtWmh4VTJHNTFDVzAKaf+brySyIb0HCdquAGmj91fF+6TTfW/4
            epEn/pPydZKJ6PfZUcJF5oU3dE72r93XAz08EFiL0aPCM4Bx/tKeFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T10:02:52Z"
    mac: ENC[AES256_GCM,data:gnB+Z0DsvSaUS+B1g18/52TwQeCX9x4piU1CDwFb97kXZX9YZlVYjiwtChpHwg8MAdZLpFptYV5teqTKrqXnrnKYdDl5Q+fS6rAx+Ul2hybJNUGlPoVe3qBa8PzMoEl5PRh+pwMMO8FC6k771oXmjYCwuGISUh6Q+LBjMBKoeqY=,iv:6y9wY4sIryAOicTSWB5iouLEDsx7vDgxb4p6ujogqbY=,tag:1fmq+BWpCNdp67qLk7i9Mg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
