apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secret
type: Opaque
stringData:
  TZ: Europe/Ljubljana
  ZIGBEE2MQTT_DATA: /data
  ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/ttyUSB0
  ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED: "false"
  ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: "115200"
  ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
  ZIGBEE2MQTT_CONFIG_MQTT_VERSION: "5"
  ZIGBEE2MQTT_CONFIG_MQTT_USER: zigbee2mqtt
  ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto.mosquitto
  ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "{{ .Values.custom.mqtt_password }}"
  ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: "60"
  ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
  ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
  ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
  ZIGBEE2MQTT_CONFIG_FRONTEND: "false"
  ZIGBEE2MQTT_CONFIG_FRONTEND_URL: "https://{{ .Values.custom.zigbee_domain }}"
  ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: "8080"
  ZIGBEE2MQTT_CONFIG_FRONTEND_AUTH_TOKEN: "{{ .Values.custom.auth_token }}"
  ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
  ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
  ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
  ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: "2000"
  ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: "60"
  ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: "{{ .Values.custom.pan_id }}"
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: "{{ .Values.custom.network_key }}"
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info # debug
  ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
  ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
  ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS: "false"
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "false"
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
