targets:
    - endpoint: ENC[AES256_GCM,data:Eqs5scWwtDgAGNpKyg==,iv:01hfKC7DJW+b61E3cjDDaeFGjjtRQJLg+tQlxQp/Jwg=,tag:QQTHxRHpPK9OKZ8zkOxoOA==,type:str]
      module: ENC[AES256_GCM,data:lhh1WA==,iv:J1KhmGfRQ8mfKJkcIZbr4hnN24kfyEmRkyCV0U8RUe4=,tag:LYheTu3/lMJ4D7hjPQ9HSw==,type:str]
      name: ENC[AES256_GCM,data:PlxjowN0I7k=,iv:0Uoh3stIuFQTB9P9TomyXswCCG23vJzmSyztlQSGZ84=,tag:pd6pCzrDym/wgF109m3ZFQ==,type:str]
    - endpoint: ENC[AES256_GCM,data:S2+SgZMnYbBYpU664A==,iv:I4CLXmZSNInczrjH7zr+XvsJpO7VWtWy5Cdf3RwpALM=,tag:HVXHmpmH7sfqaS3ovH8y4g==,type:str]
      module: ENC[AES256_GCM,data:lhh1WA==,iv:J1KhmGfRQ8mfKJkcIZbr4hnN24kfyEmRkyCV0U8RUe4=,tag:LYheTu3/lMJ4D7hjPQ9HSw==,type:str]
      name: ENC[AES256_GCM,data:Pv0sP4GZtZs=,iv:MjlGnyf0z0DDhiVbmuE3U3JyS4mRNLuDx8j4p0nQ8d8=,tag:+q46Okk3szDeWv1honzo6w==,type:str]
    - endpoint: ENC[AES256_GCM,data:qZzq9uBbcD9y6aYV2Q==,iv:Z3KkHlei8sIVXAdQE7zAypRMtTpuaHcSYl5Xh6bUwUw=,tag:jWxbY/vX9Lou1Ya2+zwOBg==,type:str]
      module: ENC[AES256_GCM,data:lhh1WA==,iv:J1KhmGfRQ8mfKJkcIZbr4hnN24kfyEmRkyCV0U8RUe4=,tag:LYheTu3/lMJ4D7hjPQ9HSw==,type:str]
      name: ENC[AES256_GCM,data:Pt2h+PAv/DA=,iv:bW/PMoetGwUBkCfgqKydFmWL+PPmdRU060mKrFBScoc=,tag:E5SuQqfn9NA2Gr/O8//vAg==,type:str]
    - endpoint: ENC[AES256_GCM,data:1LvScBYoSjGJRKMR,iv:1FVzYuaAib1i0JQgjp8I51lIW2UM9ySd5fyD6n2m5EI=,tag:oIOVx4p3OJ2e/dhB3wFn8Q==,type:str]
      module: ENC[AES256_GCM,data:lhh1WA==,iv:J1KhmGfRQ8mfKJkcIZbr4hnN24kfyEmRkyCV0U8RUe4=,tag:LYheTu3/lMJ4D7hjPQ9HSw==,type:str]
      name: ENC[AES256_GCM,data:k/kGy3lTKngMW8E=,iv:hvMtvgfLSm5WeRwykrbNVuazLNwmJJjY+891kl0LOJY=,tag:mznmRxXRdJ84Nrh9qSipTA==,type:str]
    - endpoint: ENC[AES256_GCM,data:O82sv32ZpHO3nPrPHA==,iv:f+kvdGQPbAPxLERXP+SKxeq/3/MtGjqSk4TH8TNJlIE=,tag:UMzo8+CCb1mlalsSVe2Caw==,type:str]
      module: ENC[AES256_GCM,data:lhh1WA==,iv:J1KhmGfRQ8mfKJkcIZbr4hnN24kfyEmRkyCV0U8RUe4=,tag:LYheTu3/lMJ4D7hjPQ9HSw==,type:str]
      name: ENC[AES256_GCM,data:KfS2/EA8O+E=,iv:9Esio0MBoHzj5+tg4VMPaaiWFiPsBSpJ0QmK4jbBCBs=,tag:dZsN8hDs9EPOpMWclNxXnw==,type:str]
    - endpoint: ENC[AES256_GCM,data:+Rbzm29OzPCks7LyEuM6H+oi,iv:Ewvt9/oBOo9OG9xIWYGAzpfjaHgOI7muJSKoiqPcSHA=,tag:VY4e7PZ6xnEO45zCpT/INA==,type:str]
      module: ENC[AES256_GCM,data:lhh1WA==,iv:J1KhmGfRQ8mfKJkcIZbr4hnN24kfyEmRkyCV0U8RUe4=,tag:LYheTu3/lMJ4D7hjPQ9HSw==,type:str]
      name: ENC[AES256_GCM,data:ZSf1bIiQrGIDX23QPw==,iv:PNRBIhh/DA/GMWAjVAsZaJD7k2dbngcjJTCFd9V4pt8=,tag:ePD5Yu0k7sCB4qr2uzBOfA==,type:str]
    - endpoint: ENC[AES256_GCM,data:bmWj040VLZyBnku65Q==,iv:0DEqLPXImoK14TIf9/ViZI1UoAoLuvxLfeHOU1GP8Lg=,tag:J4csMfA+uaXspOYU3kTzwg==,type:str]
      module: ENC[AES256_GCM,data:lhh1WA==,iv:J1KhmGfRQ8mfKJkcIZbr4hnN24kfyEmRkyCV0U8RUe4=,tag:LYheTu3/lMJ4D7hjPQ9HSw==,type:str]
      name: ENC[AES256_GCM,data:z8QCgtuoD2M=,iv:h5kK4zdCi336G+PJdPGonNqFObJXuYnBNk3bzZ6jJTs=,tag:Hnnpi5OUXaD5GTBIzR0urQ==,type:str]
    - endpoint: ENC[AES256_GCM,data:uKtfnZ4WxLvSbqAdYIplvps=,iv:l5BLpbIeTr0i7CRsQziibz9APfX3aL8hK0rRbemSK74=,tag:3u5RRaxsUyv5Xv9oC90DjA==,type:str]
      module: ENC[AES256_GCM,data:lhh1WA==,iv:J1KhmGfRQ8mfKJkcIZbr4hnN24kfyEmRkyCV0U8RUe4=,tag:LYheTu3/lMJ4D7hjPQ9HSw==,type:str]
      name: ENC[AES256_GCM,data:PeCWtL4Myo2Sntx7,iv:hHXrvflwen6b0cx8dOd/M+d+a4aOoJT/aw2g23mQl4I=,tag:vNGVq0Ukf1Lyiy75GUI5rg==,type:str]
    - endpoint: ENC[AES256_GCM,data:mWkHjG8C9Ho0eVM/c4HcadgRaHA5x68LJWrUqlzzv74=,iv:QW4E9VJWXJklk45YhDtjhANY1Mq6xdm30HawcNj6+rw=,tag:UTiJD1egE6dW+p+NpUTrkg==,type:str]
      module: ENC[AES256_GCM,data:lhh1WA==,iv:J1KhmGfRQ8mfKJkcIZbr4hnN24kfyEmRkyCV0U8RUe4=,tag:LYheTu3/lMJ4D7hjPQ9HSw==,type:str]
      name: ENC[AES256_GCM,data:TytciuxfGEAQ0zWTgVk38g9wLeJjZOQ=,iv:YhevZbBGhEp++RtH/o/4lnCFkbeyog6bCca9ZyDAhk4=,tag:b1F9hYMhyjJ02sEXspK7WQ==,type:str]
    - endpoint: ENC[AES256_GCM,data:mUTFBHHvZz32czmx2gghxCCB6QPwAYYZK2Aiyw==,iv:Bfk+j+lYBnNa+ZnZuZ7bDfoSr+mn2qpH18okI332NaI=,tag:mmwdPrsr2a/D8TTD4rp4Yg==,type:str]
      module: ENC[AES256_GCM,data:lhh1WA==,iv:J1KhmGfRQ8mfKJkcIZbr4hnN24kfyEmRkyCV0U8RUe4=,tag:LYheTu3/lMJ4D7hjPQ9HSw==,type:str]
      name: ENC[AES256_GCM,data:64SmPtKDmevNFyj8H9JXBYnAAQ==,iv:imqoV6qy9l9RiSoys5Y7jr/Km9Bcf1t2kYaHKlYa4p0=,tag:qMEA7QILlrEjBl7I1fxe7A==,type:str]
    - endpoint: ENC[AES256_GCM,data:IH0nbijD5wVW,iv:zd7KW51zhToRbkqsPQr3nZFYEINvLaG7MJfo3ePWt7I=,tag:KjhZN873EzxY4T5UoZzIQg==,type:str]
      module: ENC[AES256_GCM,data:zZdQzsWAAhZENRDn,iv:pFm4Zs2xnp30CsEMDnc8s2TiAtS2lXPsPWTB6KaSYBo=,tag:BzjYPNId7NlK4FiYgAC8kg==,type:str]
      name: ENC[AES256_GCM,data:0N1vPrGDFOji1eqV,iv:FSR39ikiHRCUk46MjJPjgm2BZdqTeot7IYiVWgO9LGI=,tag:G2qJt6zKhyiRpBNIBLkPRw==,type:str]
    - endpoint: ENC[AES256_GCM,data:IH0nbijD5wVW,iv:zd7KW51zhToRbkqsPQr3nZFYEINvLaG7MJfo3ePWt7I=,tag:KjhZN873EzxY4T5UoZzIQg==,type:str]
      module: ENC[AES256_GCM,data:r3OhIFNp8w==,iv:ECLz7OhkItiuy7y9GrvD5fQkKNZn+1Hqxrr6ueor7ug=,tag:/xGBR01+r8tEmdaZC49DgQ==,type:str]
      name: ENC[AES256_GCM,data:0r2TEoEAHg==,iv:PxF1aFfAI47SvfiSgFKQ/2mE/Z4Tca2KI7UoFhw/T5c=,tag:GToJ5yzjQcza1/q9qQEfSA==,type:str]
    - endpoint: ENC[AES256_GCM,data:IH0nbijD5wVW,iv:zd7KW51zhToRbkqsPQr3nZFYEINvLaG7MJfo3ePWt7I=,tag:KjhZN873EzxY4T5UoZzIQg==,type:str]
      module: ENC[AES256_GCM,data:ISyRIUIpP3pZ+g==,iv:CodGFybRg7UKry8HxU8MgCOg7kMa7rV237NPdEK1cQ0=,tag:eIpUxTRlBZMf73bFro4WBA==,type:str]
      name: ENC[AES256_GCM,data:h6QxwSudJTH2rg==,iv:8U0kVCi+EjM12S+QbUFdwKsJVBNN0V1EJ1FlGH7TjLo=,tag:XHWJsrwquzTkqRBLKMmJcw==,type:str]
    - endpoint: ENC[AES256_GCM,data:FcIYJLZUw8PF6KyyE7MEnsQ=,iv:vaU7l0pUXUkK8awl7tbxMLZRpPOxGlxKWcB3iYS4oO4=,tag:tP8bKTvMa/DImme8iWeNfg==,type:str]
      module: ENC[AES256_GCM,data:bVrq,iv:RFC/zD5p0kX7xq2QmGMfykn4qsZZGQJdyNa6mmPtHRg=,tag:k+63dgtUfPxMv70MQxdpUw==,type:str]
      name: ENC[AES256_GCM,data:6JwZsZNLOg==,iv:E8Euflv1lWcSX5Xcwhmv9lkSIMUm7SolbwJMo8ZN+Hk=,tag:QcQxeX+swFW6yZqszahjvQ==,type:str]
    - endpoint: ENC[AES256_GCM,data:RLFuot9fqRTs9vKgo2pkFzZVX26RSYD2XRJODg==,iv:CkpE5G89Orw54jH7br7OaoPB3x4DUMN03SRXmuVLIK0=,tag:1y9OU6LppHBiZ+8XTe2y9A==,type:str]
      module: ENC[AES256_GCM,data:bVrq,iv:RFC/zD5p0kX7xq2QmGMfykn4qsZZGQJdyNa6mmPtHRg=,tag:k+63dgtUfPxMv70MQxdpUw==,type:str]
      name: ENC[AES256_GCM,data:CzafVqM=,iv:lf5lrX+giRU0x7n2xTlEeB3fckpEDk8T43w2JGvrhrQ=,tag:TkeweyeT6jBEQrJNy6qZ2g==,type:str]
prometheus-blackbox-exporter:
    ingress:
        annotations:
            nginx.ingress.kubernetes.io/auth-signin: ENC[AES256_GCM,data:GwzNxJCkFPoo6EFuPGP0agRAwb/J5k+GgWF7,iv:6gKNv/o1afndx8zyEVtaI2l+tHxV/wg89OHHIPVBopI=,tag:OM/bsE0L6BnAgMMh1K1GiQ==,type:str]
        hosts:
            - host: ENC[AES256_GCM,data:u+FeJQC5XhSJ0QO9HffqQpY=,iv:ZutBVg7fIk/WesoI/VbgR0tX7RlzUJ9fPQhphQ2xdi4=,tag:CSdBkfD3BdnHjdRpUoZ0Bw==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:pA==,iv:EzfrNqheXOdl7G5EsHrN2Um0RAMoM7Y9k55NlSU3UoE=,tag:63NXZv/QZ1LEyepQhldpkg==,type:str]
                  pathType: ENC[AES256_GCM,data:GuT9If83,iv:ccCU5ZPVj+1RXGFV9QazZJoWnfxONSglu63MxWA//gE=,tag:DLYr+2HS0ke7Z/KPeNo7dw==,type:str]
        tls:
            - hosts:
                - ENC[AES256_GCM,data:TjGvXZShRKhE7MXUwwZgmT8=,iv:M1VLY/63Uw8hiq2KnTTsN63stcz9el8EDjpy/5OsG4g=,tag:V2/GxNA7JzcwTou109bQQw==,type:str]
    config:
        modules:
            dns_k8s:
                prober: ENC[AES256_GCM,data:8doI,iv:xR3TNw4CWsSY4beEMGpXInhYk1qQ05OhZDYzuSwLSA0=,tag:YYa1DAlM2fEBIgrLMKfhmA==,type:str]
                timeout: ENC[AES256_GCM,data:Za0=,iv:VPwJ1/KjGD2qM9iOc3nFLzNbgeaHzIKf4SKpQUvfU50=,tag:ZmvdKK/pmvTG+EkSHJ50Sw==,type:str]
                dns:
                    query_name: ENC[AES256_GCM,data:gQKlCs8CkB9ArMT0,iv:egarIUz6fGQNeTZINAwIgQiFCIjM3glaJ051/92Sgtc=,tag:c3e95X1eXWPCts7CqzH2SQ==,type:str]
                    query_type: ENC[AES256_GCM,data:0Q==,iv:1kpdKpGOYEpcilfhpCufWV56JeOPy7C3rdc5Y8eKmKo=,tag:s13Dqje+8uyGoe3QU6VBsA==,type:str]
                    valid_rcodes:
                        - ENC[AES256_GCM,data:s48vFae34A==,iv:2NM5jQp7+cKSfo0iukNSfG9VbPSwi0Lq+kWt34W6agQ=,tag:bfJckXqvGFJEkfwKMmpgiw==,type:str]
                    validate_answer_rrs:
                        fail_if_not_matches_regexp:
                            - ENC[AES256_GCM,data:Q0AbenXFy6yTWJ21Dg==,iv:ExblDdi2gN1TTkOOvh1CM77DxwZeezLwsmSrZ1VXl4I=,tag:QvVtDy3NsQASujsTC/BxLA==,type:str]
            dns_custom:
                prober: ENC[AES256_GCM,data:5z77,iv:Tne4OBf0BTBTTfqclDQwhX7zgkaAU52eG5cEfIkwKZ4=,tag:Vq8n1mmKO932iVy+GznzXg==,type:str]
                timeout: ENC[AES256_GCM,data:+5g=,iv:Ke8i5MOA/3lteX3BXwsf1WDMlq3IbAWFNgljXEj6NN4=,tag:qo+cTKH35BkbrnOdrurblg==,type:str]
                dns:
                    query_name: ENC[AES256_GCM,data:0nIJVh7l36Tl+p0Ehw==,iv:CXIosDccO3KTa2WWw5HKtmTJUrF/xLhuciBi/7J4HUU=,tag:bbt4QMIZCEPCDikH3sebvw==,type:str]
                    query_type: ENC[AES256_GCM,data:vQ==,iv:84JwtCoFJDhkiAwPIOfcSqzHUWj3nd2WnmSTgdaYcAk=,tag:ejF718wocEOI3jgH6jvtCw==,type:str]
                    valid_rcodes:
                        - ENC[AES256_GCM,data:og7uFEJsbQ==,iv:IERKJwseNGuDzEK4bEM4ndzhVaZSIDv70WPYJ0vePO8=,tag:Cf1S1gBzEXnkntQvyGXBsQ==,type:str]
                    validate_answer_rrs:
                        fail_if_not_matches_regexp:
                            - ENC[AES256_GCM,data:AB4cTZMe+jqfqd9u,iv:rJh4URZAjtSGfvnVu6EA8gfyCYKP2YiNpb2fwB1XcKQ=,tag:zPQtiuudwJHfE+Tq/xKoJw==,type:str]
sops:
    age:
        - recipient: age182geyhwxahnsvcexmjgw4znm5ceulnvdlm5as9x0dqa3j39nrukqua6p5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTk1UbHY3WUdCaE4yZ1lJ
            MHRlR2JoM01Hc2lDUWp3bExQeS9sLzRObG5NCmdjeHZORzQ5MGJxWno0SzBLUCtS
            UUYxL3RwZHVTRmtYYmNBejhLdXBtQVEKLS0tIDZSWjdpTnh0aXAyWTBkSm0zQURm
            STlqMnpPTkxYbXBZNENVU0tySkdCblEK/nITJNLLVfX47J3IyS69b5f91g0/aDVZ
            slUlx39gDFAE5o9mRkVW2sZybtP/yDDXyAyur52J2HaX8UEoS478Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T08:23:50Z"
    mac: ENC[AES256_GCM,data:SEBqKqvwCPNf/XodURxdlxRy+KB8g6CLfKcWg2cUh6lqXog4RHDIi3538Q/cGUdvHX8ShnKbeeox9gxyHE6eCnnp2oyheVY+E5aCEh/WvrPxruxgD9DWtJlZDxGY03kJ1W5R3RX3THz+2Zri/Z0NFH0UochXQk+S9w8l4NtvqDM=,iv:Od3uewWwxc2i4CGILO3iQ5P7DbwOxmjtOBGnuzuDJ5s=,tag:XRlt2KK8HRIfouLtURF4Uw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
