apiVersion: v1
kind: ConfigMap
metadata:
  name: autobrr-config
data:
  config.toml: |-
    host = "0.0.0.0"
    port = 80
    logLevel = "INFO"
    sessionSecret = "secret-session-key"
    oidcEnabled = true
    oidcIssuer = "https://pocket.mfin.app"
    oidcClientId = "autobrr"
    oidcRedirectUrl = "https://autobrr.mfin.app/api/auth/oidc/callback"
    oidcDisableBuiltInLogin = true
