apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-quantum
data:
  config.yaml: |-
    server:
      database: /data/database.db
      cacheDir: /data/cache
      sources:
        - path: /data/public
          config:
            defaultEnabled: true
